// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: mall.proto

package server

import (
	"context"

	"budgetmatch-sim/services/rpc/mall/internal/logic/productservice"
	"budgetmatch-sim/services/rpc/mall/internal/svc"
	"budgetmatch-sim/services/rpc/mall/pb"
)

type ProductServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedProductServiceServer
}

func NewProductServiceServer(svcCtx *svc.ServiceContext) *ProductServiceServer {
	return &ProductServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServiceServer) CreateProduct(ctx context.Context, in *pb.CreateProductReq) (*pb.CreateProductResp, error) {
	l := productservicelogic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *ProductServiceServer) UpdateProduct(ctx context.Context, in *pb.UpdateProductReq) (*pb.UpdateProductResp, error) {
	l := productservicelogic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

func (s *ProductServiceServer) DeleteProduct(ctx context.Context, in *pb.DeleteProductReq) (*pb.DeleteProductResp, error) {
	l := productservicelogic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}

func (s *ProductServiceServer) GetProduct(ctx context.Context, in *pb.GetProductReq) (*pb.GetProductResp, error) {
	l := productservicelogic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductServiceServer) ListProducts(ctx context.Context, in *pb.ListProductsReq) (*pb.ListProductsResp, error) {
	l := productservicelogic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}

func (s *ProductServiceServer) CreateSku(ctx context.Context, in *pb.CreateSkuReq) (*pb.CreateSkuResp, error) {
	l := productservicelogic.NewCreateSkuLogic(ctx, s.svcCtx)
	return l.CreateSku(in)
}

func (s *ProductServiceServer) UpdateSku(ctx context.Context, in *pb.UpdateSkuReq) (*pb.UpdateSkuResp, error) {
	l := productservicelogic.NewUpdateSkuLogic(ctx, s.svcCtx)
	return l.UpdateSku(in)
}

func (s *ProductServiceServer) DeleteSku(ctx context.Context, in *pb.DeleteSkuReq) (*pb.DeleteSkuResp, error) {
	l := productservicelogic.NewDeleteSkuLogic(ctx, s.svcCtx)
	return l.DeleteSku(in)
}

func (s *ProductServiceServer) GetSku(ctx context.Context, in *pb.GetSkuReq) (*pb.GetSkuResp, error) {
	l := productservicelogic.NewGetSkuLogic(ctx, s.svcCtx)
	return l.GetSku(in)
}

func (s *ProductServiceServer) ListSkusByProduct(ctx context.Context, in *pb.ListSkusByProductReq) (*pb.ListSkusByProductResp, error) {
	l := productservicelogic.NewListSkusByProductLogic(ctx, s.svcCtx)
	return l.ListSkusByProduct(in)
}
