// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: mall.proto

package server

import (
	"context"

	"budgetmatch-sim/services/rpc/mall/internal/logic/orderservice"
	"budgetmatch-sim/services/rpc/mall/internal/svc"
	"budgetmatch-sim/services/rpc/mall/pb"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *pb.CreateOrderReq) (*pb.CreateOrderResp, error) {
	l := orderservicelogic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServiceServer) GetOrder(ctx context.Context, in *pb.GetOrderReq) (*pb.GetOrderResp, error) {
	l := orderservicelogic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *OrderServiceServer) ListOrders(ctx context.Context, in *pb.ListOrdersReq) (*pb.ListOrdersResp, error) {
	l := orderservicelogic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *OrderServiceServer) CancelOrder(ctx context.Context, in *pb.CancelOrderReq) (*pb.CancelOrderResp, error) {
	l := orderservicelogic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *OrderServiceServer) UpdateOrderStatus(ctx context.Context, in *pb.UpdateOrderStatusReq) (*pb.UpdateOrderStatusResp, error) {
	l := orderservicelogic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}

func (s *OrderServiceServer) ConfirmPayment(ctx context.Context, in *pb.ConfirmPaymentReq) (*pb.ConfirmPaymentResp, error) {
	l := orderservicelogic.NewConfirmPaymentLogic(ctx, s.svcCtx)
	return l.ConfirmPayment(in)
}
