// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package server

import (
	"context"

	"budgetmatch-sim/services/rpc/seckill/internal/logic/skuservice"
	"budgetmatch-sim/services/rpc/seckill/internal/svc"
	"budgetmatch-sim/services/rpc/seckill/pb"
)

type SkuServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSkuServiceServer
}

func NewSkuServiceServer(svcCtx *svc.ServiceContext) *SkuServiceServer {
	return &SkuServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SkuServiceServer) CreateSku(ctx context.Context, in *pb.CreateSkuReq) (*pb.CreateSkuResp, error) {
	l := skuservicelogic.NewCreateSkuLogic(ctx, s.svcCtx)
	return l.CreateSku(in)
}

func (s *SkuServiceServer) UpdateSku(ctx context.Context, in *pb.UpdateSkuReq) (*pb.UpdateSkuResp, error) {
	l := skuservicelogic.NewUpdateSkuLogic(ctx, s.svcCtx)
	return l.UpdateSku(in)
}

func (s *SkuServiceServer) GetSku(ctx context.Context, in *pb.GetSkuReq) (*pb.GetSkuResp, error) {
	l := skuservicelogic.NewGetSkuLogic(ctx, s.svcCtx)
	return l.GetSku(in)
}

func (s *SkuServiceServer) ListSkusByActivity(ctx context.Context, in *pb.ListSkusByActivityReq) (*pb.ListSkusByActivityResp, error) {
	l := skuservicelogic.NewListSkusByActivityLogic(ctx, s.svcCtx)
	return l.ListSkusByActivity(in)
}

func (s *SkuServiceServer) DeleteSku(ctx context.Context, in *pb.DeleteSkuReq) (*pb.DeleteSkuResp, error) {
	l := skuservicelogic.NewDeleteSkuLogic(ctx, s.svcCtx)
	return l.DeleteSku(in)
}
