// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package server

import (
	"context"

	"budgetmatch-sim/services/rpc/seckill/internal/logic/seckillservice"
	"budgetmatch-sim/services/rpc/seckill/internal/svc"
	"budgetmatch-sim/services/rpc/seckill/pb"
)

type SeckillServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSeckillServiceServer
}

func NewSeckillServiceServer(svcCtx *svc.ServiceContext) *SeckillServiceServer {
	return &SeckillServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *SeckillServiceServer) AcquireToken(ctx context.Context, in *pb.AcquireTokenReq) (*pb.AcquireTokenResp, error) {
	l := seckillservicelogic.NewAcquireTokenLogic(ctx, s.svcCtx)
	return l.AcquireToken(in)
}

func (s *SeckillServiceServer) SubmitOrder(ctx context.Context, in *pb.SubmitOrderReq) (*pb.SubmitOrderResp, error) {
	l := seckillservicelogic.NewSubmitOrderLogic(ctx, s.svcCtx)
	return l.SubmitOrder(in)
}

func (s *SeckillServiceServer) GetOrder(ctx context.Context, in *pb.GetOrderReq) (*pb.GetOrderResp, error) {
	l := seckillservicelogic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}
