// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/rpc/mall/proto/mall.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2
	OrderStatus_ORDER_STATUS_SHIPPED     OrderStatus = 3
	OrderStatus_ORDER_STATUS_COMPLETED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
	OrderStatus_ORDER_STATUS_REFUNDING   OrderStatus = 6
	OrderStatus_ORDER_STATUS_REFUNDED    OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_SHIPPED",
		4: "ORDER_STATUS_COMPLETED",
		5: "ORDER_STATUS_CANCELLED",
		6: "ORDER_STATUS_REFUNDING",
		7: "ORDER_STATUS_REFUNDED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PAID":        2,
		"ORDER_STATUS_SHIPPED":     3,
		"ORDER_STATUS_COMPLETED":   4,
		"ORDER_STATUS_CANCELLED":   5,
		"ORDER_STATUS_REFUNDING":   6,
		"ORDER_STATUS_REFUNDED":    7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_rpc_mall_proto_mall_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_services_rpc_mall_proto_mall_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_UNPAID      PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PAID        PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_ABNORMAL    PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_UNPAID",
		2: "PAYMENT_STATUS_PAID",
		3: "PAYMENT_STATUS_ABNORMAL",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_UNPAID":      1,
		"PAYMENT_STATUS_PAID":        2,
		"PAYMENT_STATUS_ABNORMAL":    3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_rpc_mall_proto_mall_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_services_rpc_mall_proto_mall_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{1}
}

// ///////////////////// 基础类型 ///////////////////////
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Providor      string                 `protobuf:"bytes,6,opt,name=providor,proto3" json:"providor,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	AgentComment  string                 `protobuf:"bytes,8,opt,name=agent_comment,json=agentComment,proto3" json:"agent_comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Product) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Product) GetProvidor() string {
	if x != nil {
		return x.Providor
	}
	return ""
}

func (x *Product) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Product) GetAgentComment() string {
	if x != nil {
		return x.AgentComment
	}
	return ""
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Sku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Specs         string                 `protobuf:"bytes,4,opt,name=specs,proto3" json:"specs,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Sold          int64                  `protobuf:"varint,7,opt,name=sold,proto3" json:"sold,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	AgentComment  string                 `protobuf:"bytes,9,opt,name=agent_comment,json=agentComment,proto3" json:"agent_comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sku) Reset() {
	*x = Sku{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sku) ProtoMessage() {}

func (x *Sku) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sku.ProtoReflect.Descriptor instead.
func (*Sku) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{1}
}

func (x *Sku) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sku) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Sku) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sku) GetSpecs() string {
	if x != nil {
		return x.Specs
	}
	return ""
}

func (x *Sku) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Sku) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Sku) GetSold() int64 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *Sku) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Sku) GetAgentComment() string {
	if x != nil {
		return x.AgentComment
	}
	return ""
}

func (x *Sku) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Sku) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Providor      string                 `protobuf:"bytes,5,opt,name=providor,proto3" json:"providor,omitempty"`
	AgentComment  string                 `protobuf:"bytes,6,opt,name=agent_comment,json=agentComment,proto3" json:"agent_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateProductReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateProductReq) GetProvidor() string {
	if x != nil {
		return x.Providor
	}
	return ""
}

func (x *CreateProductReq) GetAgentComment() string {
	if x != nil {
		return x.AgentComment
	}
	return ""
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProductResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Providor      string                 `protobuf:"bytes,6,opt,name=providor,proto3" json:"providor,omitempty"`
	AgentComment  string                 `protobuf:"bytes,7,opt,name=agent_comment,json=agentComment,proto3" json:"agent_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateProductReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateProductReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UpdateProductReq) GetProvidor() string {
	if x != nil {
		return x.Providor
	}
	return ""
}

func (x *UpdateProductReq) GetAgentComment() string {
	if x != nil {
		return x.AgentComment
	}
	return ""
}

type UpdateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResp) Reset() {
	*x = UpdateProductResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResp) ProtoMessage() {}

func (x *UpdateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResp.ProtoReflect.Descriptor instead.
func (*UpdateProductResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReq) Reset() {
	*x = DeleteProductReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReq) ProtoMessage() {}

func (x *DeleteProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReq.ProtoReflect.Descriptor instead.
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProductReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResp) Reset() {
	*x = DeleteProductResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResp) ProtoMessage() {}

func (x *DeleteProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResp.ProtoReflect.Descriptor instead.
func (*DeleteProductResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReq) Reset() {
	*x = GetProductReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReq) ProtoMessage() {}

func (x *GetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReq.ProtoReflect.Descriptor instead.
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResp) Reset() {
	*x = GetProductResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResp) ProtoMessage() {}

func (x *GetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResp.ProtoReflect.Descriptor instead.
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductResp) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReq) Reset() {
	*x = ListProductsReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReq) ProtoMessage() {}

func (x *ListProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReq.ProtoReflect.Descriptor instead.
func (*ListProductsReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListProductsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListProductsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Product             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResp) Reset() {
	*x = ListProductsResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResp) ProtoMessage() {}

func (x *ListProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResp.ProtoReflect.Descriptor instead.
func (*ListProductsResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{11}
}

func (x *ListProductsResp) GetList() []*Product {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListProductsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateSkuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Specs         string                 `protobuf:"bytes,3,opt,name=specs,proto3" json:"specs,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	AgentComment  string                 `protobuf:"bytes,6,opt,name=agent_comment,json=agentComment,proto3" json:"agent_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkuReq) Reset() {
	*x = CreateSkuReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkuReq) ProtoMessage() {}

func (x *CreateSkuReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkuReq.ProtoReflect.Descriptor instead.
func (*CreateSkuReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSkuReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateSkuReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSkuReq) GetSpecs() string {
	if x != nil {
		return x.Specs
	}
	return ""
}

func (x *CreateSkuReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSkuReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateSkuReq) GetAgentComment() string {
	if x != nil {
		return x.AgentComment
	}
	return ""
}

type CreateSkuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkuResp) Reset() {
	*x = CreateSkuResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkuResp) ProtoMessage() {}

func (x *CreateSkuResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkuResp.ProtoReflect.Descriptor instead.
func (*CreateSkuResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSkuResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSkuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Specs         string                 `protobuf:"bytes,3,opt,name=specs,proto3" json:"specs,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	AgentComment  string                 `protobuf:"bytes,7,opt,name=agent_comment,json=agentComment,proto3" json:"agent_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkuReq) Reset() {
	*x = UpdateSkuReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkuReq) ProtoMessage() {}

func (x *UpdateSkuReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkuReq.ProtoReflect.Descriptor instead.
func (*UpdateSkuReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSkuReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSkuReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSkuReq) GetSpecs() string {
	if x != nil {
		return x.Specs
	}
	return ""
}

func (x *UpdateSkuReq) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateSkuReq) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateSkuReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateSkuReq) GetAgentComment() string {
	if x != nil {
		return x.AgentComment
	}
	return ""
}

type UpdateSkuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSkuResp) Reset() {
	*x = UpdateSkuResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSkuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSkuResp) ProtoMessage() {}

func (x *UpdateSkuResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSkuResp.ProtoReflect.Descriptor instead.
func (*UpdateSkuResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateSkuResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteSkuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkuReq) Reset() {
	*x = DeleteSkuReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkuReq) ProtoMessage() {}

func (x *DeleteSkuReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkuReq.ProtoReflect.Descriptor instead.
func (*DeleteSkuReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSkuReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteSkuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSkuResp) Reset() {
	*x = DeleteSkuResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSkuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkuResp) ProtoMessage() {}

func (x *DeleteSkuResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkuResp.ProtoReflect.Descriptor instead.
func (*DeleteSkuResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteSkuResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSkuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkuReq) Reset() {
	*x = GetSkuReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkuReq) ProtoMessage() {}

func (x *GetSkuReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkuReq.ProtoReflect.Descriptor instead.
func (*GetSkuReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{18}
}

func (x *GetSkuReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSkuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *Sku                   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkuResp) Reset() {
	*x = GetSkuResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkuResp) ProtoMessage() {}

func (x *GetSkuResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkuResp.ProtoReflect.Descriptor instead.
func (*GetSkuResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{19}
}

func (x *GetSkuResp) GetSku() *Sku {
	if x != nil {
		return x.Sku
	}
	return nil
}

type ListSkusByProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkusByProductReq) Reset() {
	*x = ListSkusByProductReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkusByProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkusByProductReq) ProtoMessage() {}

func (x *ListSkusByProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkusByProductReq.ProtoReflect.Descriptor instead.
func (*ListSkusByProductReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{20}
}

func (x *ListSkusByProductReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ListSkusByProductReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSkusByProductReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSkusByProductReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListSkusByProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Sku                 `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkusByProductResp) Reset() {
	*x = ListSkusByProductResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkusByProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkusByProductResp) ProtoMessage() {}

func (x *ListSkusByProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkusByProductResp.ProtoReflect.Descriptor instead.
func (*ListSkusByProductResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{21}
}

func (x *ListSkusByProductResp) GetList() []*Sku {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListSkusByProductResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSkusByProductResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSkusByProductResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId          string                 `protobuf:"bytes,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SkuName        string                 `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	Price          int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity       int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,6,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Snapshot       string                 `protobuf:"bytes,8,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{22}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *OrderItem) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *OrderItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *OrderItem) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderItem) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalAmount int64                  `protobuf:"varint,3,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	PayAmount      int64                  `protobuf:"varint,5,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	Status         OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=mall.OrderStatus" json:"status,omitempty"`
	PayType        string                 `protobuf:"bytes,7,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	PayTime        string                 `protobuf:"bytes,8,opt,name=pay_time,json=payTime,proto3" json:"pay_time,omitempty"`
	Remark         string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Snapshot       string                 `protobuf:"bytes,10,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Items          []*OrderItem           `protobuf:"bytes,12,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PaymentStatus  PaymentStatus          `protobuf:"varint,15,opt,name=payment_status,json=paymentStatus,proto3,enum=mall.PaymentStatus" json:"payment_status,omitempty"`
	OutTradeNo     string                 `protobuf:"bytes,16,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	TradeNo        string                 `protobuf:"bytes,17,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{23}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetOriginalAmount() int64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *Order) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *Order) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *Order) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *Order) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Order) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *Order) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Order) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Order) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *Order) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type CreateOrderReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkuId          string                 `protobuf:"bytes,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity       int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Remark         string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{24}
}

func (x *CreateOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderReq) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *CreateOrderReq) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateOrderReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=mall.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{25}
}

func (x *CreateOrderResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResp) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{26}
}

func (x *GetOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResp) Reset() {
	*x = GetOrderResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResp) ProtoMessage() {}

func (x *GetOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResp.ProtoReflect.Descriptor instead.
func (*GetOrderResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{27}
}

func (x *GetOrderResp) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=mall.OrderStatus" json:"status,omitempty"`
	PaymentStatus PaymentStatus          `protobuf:"varint,5,opt,name=payment_status,json=paymentStatus,proto3,enum=mall.PaymentStatus" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReq) Reset() {
	*x = ListOrdersReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReq) ProtoMessage() {}

func (x *ListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReq.ProtoReflect.Descriptor instead.
func (*ListOrdersReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{28}
}

func (x *ListOrdersReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrdersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersReq) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersReq) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type ListOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Order               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResp) Reset() {
	*x = ListOrdersResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResp) ProtoMessage() {}

func (x *ListOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResp.ProtoReflect.Descriptor instead.
func (*ListOrdersResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{29}
}

func (x *ListOrdersResp) GetList() []*Order {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOrdersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{30}
}

func (x *CancelOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResp) Reset() {
	*x = CancelOrderResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResp) ProtoMessage() {}

func (x *CancelOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResp.ProtoReflect.Descriptor instead.
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{31}
}

func (x *CancelOrderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateOrderStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=mall.OrderStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusReq) Reset() {
	*x = UpdateOrderStatusReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusReq) ProtoMessage() {}

func (x *UpdateOrderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateOrderStatusReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateOrderStatusReq) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type UpdateOrderStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResp) Reset() {
	*x = UpdateOrderStatusResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResp) ProtoMessage() {}

func (x *UpdateOrderStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateOrderStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConfirmPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` //精确到分，也就是小数点后两位
	OutTradeNo    string                 `protobuf:"bytes,4,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	TradeNo       string                 `protobuf:"bytes,5,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentReq) Reset() {
	*x = ConfirmPaymentReq{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentReq) ProtoMessage() {}

func (x *ConfirmPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentReq.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{34}
}

func (x *ConfirmPaymentReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ConfirmPaymentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmPaymentReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConfirmPaymentReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *ConfirmPaymentReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type ConfirmPaymentResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status              int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	WasAlreadyConfirmed bool                   `protobuf:"varint,3,opt,name=was_already_confirmed,json=wasAlreadyConfirmed,proto3" json:"was_already_confirmed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfirmPaymentResp) Reset() {
	*x = ConfirmPaymentResp{}
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResp) ProtoMessage() {}

func (x *ConfirmPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_mall_proto_mall_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResp.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_mall_proto_mall_proto_rawDescGZIP(), []int{35}
}

func (x *ConfirmPaymentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmPaymentResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ConfirmPaymentResp) GetWasAlreadyConfirmed() bool {
	if x != nil {
		return x.WasAlreadyConfirmed
	}
	return false
}

var File_services_rpc_mall_proto_mall_proto protoreflect.FileDescriptor

const file_services_rpc_mall_proto_mall_proto_rawDesc = "" +
	"\n" +
	"\"services/rpc/mall/proto/mall.proto\x12\x04mall\"\x8d\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1a\n" +
	"\bprovidor\x18\x06 \x01(\tR\bprovidor\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12#\n" +
	"\ragent_comment\x18\b \x01(\tR\fagentComment\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x99\x02\n" +
	"\x03Sku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05specs\x18\x04 \x01(\tR\x05specs\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x12\n" +
	"\x04sold\x18\a \x01(\x03R\x04sold\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12#\n" +
	"\ragent_comment\x18\t \x01(\tR\fagentComment\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"\xb0\x01\n" +
	"\x10CreateProductReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1a\n" +
	"\bprovidor\x18\x05 \x01(\tR\bprovidor\x12#\n" +
	"\ragent_comment\x18\x06 \x01(\tR\fagentComment\"#\n" +
	"\x11CreateProductResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbf\x01\n" +
	"\x10UpdateProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1a\n" +
	"\bprovidor\x18\x06 \x01(\tR\bprovidor\x12#\n" +
	"\ragent_comment\x18\a \x01(\tR\fagentComment\"-\n" +
	"\x11UpdateProductResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\"\n" +
	"\x10DeleteProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11DeleteProductResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1f\n" +
	"\rGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x0eGetProductResp\x12'\n" +
	"\aproduct\x18\x01 \x01(\v2\r.mall.ProductR\aproduct\"\x8d\x01\n" +
	"\x0fListProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"|\n" +
	"\x10ListProductsResp\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.mall.ProductR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa8\x01\n" +
	"\fCreateSkuReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05specs\x18\x03 \x01(\tR\x05specs\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12#\n" +
	"\ragent_comment\x18\x06 \x01(\tR\fagentComment\"\x1f\n" +
	"\rCreateSkuResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb1\x01\n" +
	"\fUpdateSkuReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05specs\x18\x03 \x01(\tR\x05specs\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x03R\x05stock\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12#\n" +
	"\ragent_comment\x18\a \x01(\tR\fagentComment\")\n" +
	"\rUpdateSkuResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\fDeleteSkuReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\rDeleteSkuResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1b\n" +
	"\tGetSkuReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\n" +
	"GetSkuResp\x12\x1b\n" +
	"\x03sku\x18\x01 \x01(\v2\t.mall.SkuR\x03sku\"~\n" +
	"\x14ListSkusByProductReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"}\n" +
	"\x15ListSkusByProductResp\x12\x1d\n" +
	"\x04list\x18\x01 \x03(\v2\t.mall.SkuR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xf6\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\tR\x05skuId\x12\x19\n" +
	"\bsku_name\x18\x03 \x01(\tR\askuName\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12'\n" +
	"\x0fdiscount_amount\x18\x06 \x01(\x03R\x0ediscountAmount\x12!\n" +
	"\ftotal_amount\x18\a \x01(\x03R\vtotalAmount\x12\x1a\n" +
	"\bsnapshot\x18\b \x01(\tR\bsnapshot\"\xbd\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0foriginal_amount\x18\x03 \x01(\x03R\x0eoriginalAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x03R\x0ediscountAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x05 \x01(\x03R\tpayAmount\x12)\n" +
	"\x06status\x18\x06 \x01(\x0e2\x11.mall.OrderStatusR\x06status\x12\x19\n" +
	"\bpay_type\x18\a \x01(\tR\apayType\x12\x19\n" +
	"\bpay_time\x18\b \x01(\tR\apayTime\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x1a\n" +
	"\bsnapshot\x18\n" +
	" \x01(\tR\bsnapshot\x12'\n" +
	"\x0fidempotency_key\x18\v \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x05items\x18\f \x03(\v2\x0f.mall.OrderItemR\x05items\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12:\n" +
	"\x0epayment_status\x18\x0f \x01(\x0e2\x13.mall.PaymentStatusR\rpaymentStatus\x12 \n" +
	"\fout_trade_no\x18\x10 \x01(\tR\n" +
	"outTradeNo\x12\x19\n" +
	"\btrade_no\x18\x11 \x01(\tR\atradeNo\"\x9d\x01\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\tR\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"W\n" +
	"\x0fCreateOrderResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.mall.OrderStatusR\x06status\"A\n" +
	"\vGetOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\fGetOrderResp\x12!\n" +
	"\x05order\x18\x01 \x01(\v2\v.mall.OrderR\x05order\"\xc0\x01\n" +
	"\rListOrdersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.mall.OrderStatusR\x06status\x12:\n" +
	"\x0epayment_status\x18\x05 \x01(\x0e2\x13.mall.PaymentStatusR\rpaymentStatus\"x\n" +
	"\x0eListOrdersResp\x12\x1f\n" +
	"\x04list\x18\x01 \x03(\v2\v.mall.OrderR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"D\n" +
	"\x0eCancelOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"+\n" +
	"\x0fCancelOrderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"u\n" +
	"\x14UpdateOrderStatusReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.mall.OrderStatusR\x06status\"1\n" +
	"\x15UpdateOrderStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9c\x01\n" +
	"\x11ConfirmPaymentReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12 \n" +
	"\fout_trade_no\x18\x04 \x01(\tR\n" +
	"outTradeNo\x12\x19\n" +
	"\btrade_no\x18\x05 \x01(\tR\atradeNo\"z\n" +
	"\x12ConfirmPaymentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x122\n" +
	"\x15was_already_confirmed\x18\x03 \x01(\bR\x13wasAlreadyConfirmed*\xe5\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x18\n" +
	"\x14ORDER_STATUS_SHIPPED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_REFUNDING\x10\x06\x12\x19\n" +
	"\x15ORDER_STATUS_REFUNDED\x10\a*\x80\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_STATUS_UNPAID\x10\x01\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_STATUS_ABNORMAL\x10\x032\xff\x04\n" +
	"\x0eProductService\x12B\n" +
	"\rCreateProduct\x12\x16.mall.CreateProductReq\x1a\x17.mall.CreateProductResp\"\x00\x12B\n" +
	"\rUpdateProduct\x12\x16.mall.UpdateProductReq\x1a\x17.mall.UpdateProductResp\"\x00\x12B\n" +
	"\rDeleteProduct\x12\x16.mall.DeleteProductReq\x1a\x17.mall.DeleteProductResp\"\x00\x129\n" +
	"\n" +
	"GetProduct\x12\x13.mall.GetProductReq\x1a\x14.mall.GetProductResp\"\x00\x12?\n" +
	"\fListProducts\x12\x15.mall.ListProductsReq\x1a\x16.mall.ListProductsResp\"\x00\x126\n" +
	"\tCreateSku\x12\x12.mall.CreateSkuReq\x1a\x13.mall.CreateSkuResp\"\x00\x126\n" +
	"\tUpdateSku\x12\x12.mall.UpdateSkuReq\x1a\x13.mall.UpdateSkuResp\"\x00\x126\n" +
	"\tDeleteSku\x12\x12.mall.DeleteSkuReq\x1a\x13.mall.DeleteSkuResp\"\x00\x12-\n" +
	"\x06GetSku\x12\x0f.mall.GetSkuReq\x1a\x10.mall.GetSkuResp\"\x00\x12N\n" +
	"\x11ListSkusByProduct\x12\x1a.mall.ListSkusByProductReq\x1a\x1b.mall.ListSkusByProductResp\"\x002\x91\x03\n" +
	"\fOrderService\x12<\n" +
	"\vCreateOrder\x12\x14.mall.CreateOrderReq\x1a\x15.mall.CreateOrderResp\"\x00\x123\n" +
	"\bGetOrder\x12\x11.mall.GetOrderReq\x1a\x12.mall.GetOrderResp\"\x00\x129\n" +
	"\n" +
	"ListOrders\x12\x13.mall.ListOrdersReq\x1a\x14.mall.ListOrdersResp\"\x00\x12<\n" +
	"\vCancelOrder\x12\x14.mall.CancelOrderReq\x1a\x15.mall.CancelOrderResp\"\x00\x12N\n" +
	"\x11UpdateOrderStatus\x12\x1a.mall.UpdateOrderStatusReq\x1a\x1b.mall.UpdateOrderStatusResp\"\x00\x12E\n" +
	"\x0eConfirmPayment\x12\x17.mall.ConfirmPaymentReq\x1a\x18.mall.ConfirmPaymentResp\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_services_rpc_mall_proto_mall_proto_rawDescOnce sync.Once
	file_services_rpc_mall_proto_mall_proto_rawDescData []byte
)

func file_services_rpc_mall_proto_mall_proto_rawDescGZIP() []byte {
	file_services_rpc_mall_proto_mall_proto_rawDescOnce.Do(func() {
		file_services_rpc_mall_proto_mall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_rpc_mall_proto_mall_proto_rawDesc), len(file_services_rpc_mall_proto_mall_proto_rawDesc)))
	})
	return file_services_rpc_mall_proto_mall_proto_rawDescData
}

var file_services_rpc_mall_proto_mall_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_services_rpc_mall_proto_mall_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_services_rpc_mall_proto_mall_proto_goTypes = []any{
	(OrderStatus)(0),              // 0: mall.OrderStatus
	(PaymentStatus)(0),            // 1: mall.PaymentStatus
	(*Product)(nil),               // 2: mall.Product
	(*Sku)(nil),                   // 3: mall.Sku
	(*CreateProductReq)(nil),      // 4: mall.CreateProductReq
	(*CreateProductResp)(nil),     // 5: mall.CreateProductResp
	(*UpdateProductReq)(nil),      // 6: mall.UpdateProductReq
	(*UpdateProductResp)(nil),     // 7: mall.UpdateProductResp
	(*DeleteProductReq)(nil),      // 8: mall.DeleteProductReq
	(*DeleteProductResp)(nil),     // 9: mall.DeleteProductResp
	(*GetProductReq)(nil),         // 10: mall.GetProductReq
	(*GetProductResp)(nil),        // 11: mall.GetProductResp
	(*ListProductsReq)(nil),       // 12: mall.ListProductsReq
	(*ListProductsResp)(nil),      // 13: mall.ListProductsResp
	(*CreateSkuReq)(nil),          // 14: mall.CreateSkuReq
	(*CreateSkuResp)(nil),         // 15: mall.CreateSkuResp
	(*UpdateSkuReq)(nil),          // 16: mall.UpdateSkuReq
	(*UpdateSkuResp)(nil),         // 17: mall.UpdateSkuResp
	(*DeleteSkuReq)(nil),          // 18: mall.DeleteSkuReq
	(*DeleteSkuResp)(nil),         // 19: mall.DeleteSkuResp
	(*GetSkuReq)(nil),             // 20: mall.GetSkuReq
	(*GetSkuResp)(nil),            // 21: mall.GetSkuResp
	(*ListSkusByProductReq)(nil),  // 22: mall.ListSkusByProductReq
	(*ListSkusByProductResp)(nil), // 23: mall.ListSkusByProductResp
	(*OrderItem)(nil),             // 24: mall.OrderItem
	(*Order)(nil),                 // 25: mall.Order
	(*CreateOrderReq)(nil),        // 26: mall.CreateOrderReq
	(*CreateOrderResp)(nil),       // 27: mall.CreateOrderResp
	(*GetOrderReq)(nil),           // 28: mall.GetOrderReq
	(*GetOrderResp)(nil),          // 29: mall.GetOrderResp
	(*ListOrdersReq)(nil),         // 30: mall.ListOrdersReq
	(*ListOrdersResp)(nil),        // 31: mall.ListOrdersResp
	(*CancelOrderReq)(nil),        // 32: mall.CancelOrderReq
	(*CancelOrderResp)(nil),       // 33: mall.CancelOrderResp
	(*UpdateOrderStatusReq)(nil),  // 34: mall.UpdateOrderStatusReq
	(*UpdateOrderStatusResp)(nil), // 35: mall.UpdateOrderStatusResp
	(*ConfirmPaymentReq)(nil),     // 36: mall.ConfirmPaymentReq
	(*ConfirmPaymentResp)(nil),    // 37: mall.ConfirmPaymentResp
}
var file_services_rpc_mall_proto_mall_proto_depIdxs = []int32{
	2,  // 0: mall.GetProductResp.product:type_name -> mall.Product
	2,  // 1: mall.ListProductsResp.list:type_name -> mall.Product
	3,  // 2: mall.GetSkuResp.sku:type_name -> mall.Sku
	3,  // 3: mall.ListSkusByProductResp.list:type_name -> mall.Sku
	0,  // 4: mall.Order.status:type_name -> mall.OrderStatus
	24, // 5: mall.Order.items:type_name -> mall.OrderItem
	1,  // 6: mall.Order.payment_status:type_name -> mall.PaymentStatus
	0,  // 7: mall.CreateOrderResp.status:type_name -> mall.OrderStatus
	25, // 8: mall.GetOrderResp.order:type_name -> mall.Order
	0,  // 9: mall.ListOrdersReq.status:type_name -> mall.OrderStatus
	1,  // 10: mall.ListOrdersReq.payment_status:type_name -> mall.PaymentStatus
	25, // 11: mall.ListOrdersResp.list:type_name -> mall.Order
	0,  // 12: mall.UpdateOrderStatusReq.status:type_name -> mall.OrderStatus
	4,  // 13: mall.ProductService.CreateProduct:input_type -> mall.CreateProductReq
	6,  // 14: mall.ProductService.UpdateProduct:input_type -> mall.UpdateProductReq
	8,  // 15: mall.ProductService.DeleteProduct:input_type -> mall.DeleteProductReq
	10, // 16: mall.ProductService.GetProduct:input_type -> mall.GetProductReq
	12, // 17: mall.ProductService.ListProducts:input_type -> mall.ListProductsReq
	14, // 18: mall.ProductService.CreateSku:input_type -> mall.CreateSkuReq
	16, // 19: mall.ProductService.UpdateSku:input_type -> mall.UpdateSkuReq
	18, // 20: mall.ProductService.DeleteSku:input_type -> mall.DeleteSkuReq
	20, // 21: mall.ProductService.GetSku:input_type -> mall.GetSkuReq
	22, // 22: mall.ProductService.ListSkusByProduct:input_type -> mall.ListSkusByProductReq
	26, // 23: mall.OrderService.CreateOrder:input_type -> mall.CreateOrderReq
	28, // 24: mall.OrderService.GetOrder:input_type -> mall.GetOrderReq
	30, // 25: mall.OrderService.ListOrders:input_type -> mall.ListOrdersReq
	32, // 26: mall.OrderService.CancelOrder:input_type -> mall.CancelOrderReq
	34, // 27: mall.OrderService.UpdateOrderStatus:input_type -> mall.UpdateOrderStatusReq
	36, // 28: mall.OrderService.ConfirmPayment:input_type -> mall.ConfirmPaymentReq
	5,  // 29: mall.ProductService.CreateProduct:output_type -> mall.CreateProductResp
	7,  // 30: mall.ProductService.UpdateProduct:output_type -> mall.UpdateProductResp
	9,  // 31: mall.ProductService.DeleteProduct:output_type -> mall.DeleteProductResp
	11, // 32: mall.ProductService.GetProduct:output_type -> mall.GetProductResp
	13, // 33: mall.ProductService.ListProducts:output_type -> mall.ListProductsResp
	15, // 34: mall.ProductService.CreateSku:output_type -> mall.CreateSkuResp
	17, // 35: mall.ProductService.UpdateSku:output_type -> mall.UpdateSkuResp
	19, // 36: mall.ProductService.DeleteSku:output_type -> mall.DeleteSkuResp
	21, // 37: mall.ProductService.GetSku:output_type -> mall.GetSkuResp
	23, // 38: mall.ProductService.ListSkusByProduct:output_type -> mall.ListSkusByProductResp
	27, // 39: mall.OrderService.CreateOrder:output_type -> mall.CreateOrderResp
	29, // 40: mall.OrderService.GetOrder:output_type -> mall.GetOrderResp
	31, // 41: mall.OrderService.ListOrders:output_type -> mall.ListOrdersResp
	33, // 42: mall.OrderService.CancelOrder:output_type -> mall.CancelOrderResp
	35, // 43: mall.OrderService.UpdateOrderStatus:output_type -> mall.UpdateOrderStatusResp
	37, // 44: mall.OrderService.ConfirmPayment:output_type -> mall.ConfirmPaymentResp
	29, // [29:45] is the sub-list for method output_type
	13, // [13:29] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_services_rpc_mall_proto_mall_proto_init() }
func file_services_rpc_mall_proto_mall_proto_init() {
	if File_services_rpc_mall_proto_mall_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_rpc_mall_proto_mall_proto_rawDesc), len(file_services_rpc_mall_proto_mall_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_services_rpc_mall_proto_mall_proto_goTypes,
		DependencyIndexes: file_services_rpc_mall_proto_mall_proto_depIdxs,
		EnumInfos:         file_services_rpc_mall_proto_mall_proto_enumTypes,
		MessageInfos:      file_services_rpc_mall_proto_mall_proto_msgTypes,
	}.Build()
	File_services_rpc_mall_proto_mall_proto = out.File
	file_services_rpc_mall_proto_mall_proto_goTypes = nil
	file_services_rpc_mall_proto_mall_proto_depIdxs = nil
}
