// Code generated by goctl. Not to edit.

package types

type RegisterReq struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6"`
	Username string `json:"username" validate:"required,min=2"`
	Code     string `json:"code" validate:"required,len=6"`
}

type RegisterResp struct {
	Success bool `json:"success"`
}

type UsernameLoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type EmailLoginReq struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId string `json:"user_id"`
	Role   int32  `json:"role"`
}

type LoginByCodeReq struct {
	Email string `json:"email" validate:"required,email"`
	Code  string `json:"code" validate:"required,len=6"`
}

type SendCodeReq struct {
	Email string `json:"email" validate:"required,email"`
}

type SendCodeResp struct {
	Success bool `json:"success"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserId   string `json:"user_id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Avatar   string `json:"avatar"`
	Phone    string `json:"phone"`
}

type UserProfileReq struct {
}

type UserProfileResp struct {
	UserId           string `json:"user_id"`
	RealName         string `json:"real_name"`
	School           string `json:"school"`
	Major            string `json:"major"`
	Grade            string `json:"grade"`
	Gender           int32  `json:"gender"`
	ExpectedCity     string `json:"expected_city"`
	ExpectedPosition string `json:"expected_position"`
	SelfIntroduction string `json:"self_introduction"`
}

type UpdateUserProfileReq struct {
	RealName         string `json:"real_name,optional"`
	School           string `json:"school,optional"`
	Major            string `json:"major,optional"`
	Grade            string `json:"grade,optional"`
	Gender           int32  `json:"gender,optional"`
	ExpectedCity     string `json:"expected_city,optional"`
	ExpectedPosition string `json:"expected_position,optional"`
	SelfIntroduction string `json:"self_introduction,optional"`
}

type UpdateUserProfileResp struct {
	Success bool `json:"success"`
}

type ActivityItem struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	BannerUrl   string `json:"banner_url"`
	StartTime   string `json:"start_time"`
	EndTime     string `json:"end_time"`
	Status      int32  `json:"status"`
	CreatedAt   string `json:"created_at"`
}

type ActivityListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
	Status   int `form:"status,default=0"`
}

type ActivityListResp struct {
	List     []ActivityItem `json:"list"`
	Total    int64          `json:"total"`
	Page     int            `json:"page"`
	PageSize int            `json:"page_size"`
}

type ActivityDetailReq struct {
	Id string `path:"id"`
}

type ActivityDetailResp struct {
	Activity ActivityItem `json:"activity"`
}

type SkuItem struct {
	Id            string `json:"id"`
	ActivityId    string `json:"activity_id"`
	Title         string `json:"title"`
	Subtitle      string `json:"subtitle"`
	Pic           string `json:"pic"`
	OriginalPrice int64  `json:"original_price"`
	SeckillPrice  int64  `json:"seckill_price"`
	Stock         int64  `json:"stock"`
	Sold          int64  `json:"sold"`
	Status        int32  `json:"status"`
	Sort          int64  `json:"sort"`
}

type SkuListReq struct {
	ActivityId string `form:"activity_id,required"`
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"page_size,default=10"`
}

type SkuListResp struct {
	List     []SkuItem `json:"list"`
	Total    int64     `json:"total"`
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`
}

type AcquireTokenReq struct {
	ActivityId string `json:"activity_id" validate:"required"`
	SkuId      string `json:"sku_id" validate:"required"`
}

type AcquireTokenResp struct {
	Token string `json:"token"`
}

type SubmitOrderReq struct {
	ActivityId string `json:"activity_id" validate:"required"`
	SkuId      string `json:"sku_id" validate:"required"`
	Token      string `json:"token" validate:"required"`
	Quantity   int64  `json:"quantity" validate:"required,min=1"`
}

type SubmitOrderResp struct {
	OrderId string `json:"order_id"`
	Status  int32  `json:"status"`
}

type GetOrderReq struct {
	OrderId string `path:"order_id"`
}

type GetOrderResp struct {
	OrderId     string `json:"order_id"`
	ActivityId  string `json:"activity_id"`
	SkuId       string `json:"sku_id"`
	Quantity    int64  `json:"quantity"`
	TotalAmount int64  `json:"total_amount"`
	Status      int32  `json:"status"`
	CreatedAt   string `json:"created_at"`
}

type MallProductItem struct {
	Id           string `json:"id"`
	UserId       string `json:"user_id"`
	Name         string `json:"name"`
	Content      string `json:"content"`
	Image        string `json:"image"`
	Providor     string `json:"providor"`
	Status       int32  `json:"status"`
	AgentComment string `json:"agent_comment"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type MallSkuItem struct {
	Id           string `json:"id"`
	ProductId    string `json:"product_id"`
	Name         string `json:"name"`
	Specs        string `json:"specs"`
	Price        int64  `json:"price"`
	Stock        int64  `json:"stock"`
	Sold         int64  `json:"sold"`
	Status       int32  `json:"status"`
	AgentComment string `json:"agent_comment"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type MallProductListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=10"`
	Keyword  string `form:"keyword"`
	Status   int32  `form:"status,default=1"`
	UserId   string `form:"user_id,optional"`
}

type MallProductListResp struct {
	List     []MallProductItem `json:"list"`
	Total    int64             `json:"total"`
	Page     int               `json:"page"`
	PageSize int               `json:"page_size"`
}

type MallProductDetailReq struct {
	Id string `path:"id"`
}

type MallProductDetailResp struct {
	Product MallProductItem `json:"product"`
}

type MallSkuListReq struct {
	ProductId string `form:"product_id,required"`
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"page_size,default=10"`
	Status    int32  `form:"status,default=1"`
}

type MallSkuListResp struct {
	List     []MallSkuItem `json:"list"`
	Total    int64         `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
}

type MallOrderItem struct {
	ProductId      string `json:"product_id"`
	SkuId          string `json:"sku_id"`
	SkuName        string `json:"sku_name"`
	Price          int64  `json:"price"`
	Quantity       int64  `json:"quantity"`
	DiscountAmount int64  `json:"discount_amount"`
	TotalAmount    int64  `json:"total_amount"`
	Snapshot       string `json:"snapshot"`
}

type MallOrderResp struct {
	Id             string          `json:"id"`
	UserId         string          `json:"user_id"`
	OriginalAmount int64           `json:"original_amount"`
	DiscountAmount int64           `json:"discount_amount"`
	PayAmount      int64           `json:"pay_amount"`
	Status         int32           `json:"status"`
	PayType        string          `json:"pay_type"`
	PayTime        string          `json:"pay_time"`
	Remark         string          `json:"remark"`
	Snapshot       string          `json:"snapshot"`
	IdempotencyKey string          `json:"idempotency_key"`
	Items          []MallOrderItem `json:"items"`
	CreatedAt      string          `json:"created_at"`
	UpdatedAt      string          `json:"updated_at"`
}

type MallCreateOrderReq struct {
	SkuId          string `json:"sku_id" validate:"required"`
	Quantity       int64  `json:"quantity" validate:"required,min=1,max=99"`
	Remark         string `json:"remark,optional"`
	IdempotencyKey string `json:"idempotency_key" validate:"required"`
}

type MallCreateOrderResp struct {
	OrderId string `json:"order_id"`
	Status  int32  `json:"status"`
}

type MallOrderListReq struct {
	Page     int   `form:"page,default=1"`
	PageSize int   `form:"page_size,default=10"`
	Status   int32 `form:"status,default=-1"`
}

type MallOrderListResp struct {
	List     []MallOrderResp `json:"list"`
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
}

type MallOrderDetailReq struct {
	Id string `path:"id"`
}

type MallOrderDetailResp struct {
	Order MallOrderResp `json:"order"`
}

type MallCancelOrderReq struct {
	Id string `path:"id"`
}

type AgentRecommendReq struct {
	Query          string `json:"query" validate:"required"`
	BudgetCents    int64  `json:"budget_cents,optional"`
	MaxItems       int    `json:"max_items,optional"`
	ConversationId string `json:"conversation_id,optional"`
}

type AgentIntent struct {
	BudgetCents int64    `json:"budget_cents"`
	MaxItems    int32    `json:"max_items"`
	Keywords    []string `json:"keywords"`
	Preferences []string `json:"preferences"`
}

type AgentBundleItem struct {
	Id         string  `json:"id"`
	Name       string  `json:"name"`
	Category   string  `json:"category"`
	Source     string  `json:"source"`
	PriceCents int64   `json:"price_cents"`
	Stock      int64   `json:"stock"`
	Score      float64 `json:"score"`
	Reason     string  `json:"reason"`
}

type AgentToolCall struct {
	Name    string `json:"name"`
	Success bool   `json:"success"`
	Detail  string `json:"detail"`
}

type AgentRecommendResp struct {
	Intent          AgentIntent       `json:"intent"`
	Items           []AgentBundleItem `json:"items"`
	TotalPriceCents int64             `json:"total_price_cents"`
	Summary         string            `json:"summary"`
	ToolsUsed       []AgentToolCall   `json:"tools_used"`
	ConversationId  string            `json:"conversation_id"`
}
