// Code generated by goctl. Not to edit.

package types

type ActivityItem struct {
	Id          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	BannerUrl   string `json:"banner_url"`
	StartTime   string `json:"start_time"`
	EndTime     string `json:"end_time"`
	Status      int32  `json:"status"`
	CreatedAt   string `json:"created_at"`
}

type ActivityListReq struct {
	Page     int `json:"page" form:"page,default=1"`
	PageSize int `json:"page_size" form:"page_size,default=10"`
	Status   int `json:"status" form:"status,default=0"`
}

type ActivityListResp struct {
	List     []ActivityItem `json:"list"`
	Total    int64          `json:"total"`
	Page     int            `json:"page"`
	PageSize int            `json:"page_size"`
}

type ActivityDetailReq struct {
	Id string `json:"id" path:"id"`
}

type ActivityDetailResp struct {
	Activity ActivityItem `json:"activity"`
}

type SkuItem struct {
	Id            string `json:"id"`
	ActivityId    string `json:"activity_id"`
	Title         string `json:"title"`
	Subtitle      string `json:"subtitle"`
	Pic           string `json:"pic"`
	OriginalPrice int64  `json:"original_price"`
	SeckillPrice  int64  `json:"seckill_price"`
	Stock         int64  `json:"stock"`
	Sold          int64  `json:"sold"`
	Status        int32  `json:"status"`
	Sort          int64  `json:"sort"`
}

type SkuListReq struct {
	ActivityId string `json:"activity_id" form:"activity_id,required"`
	Page       int    `json:"page" form:"page,default=1"`
	PageSize   int    `json:"page_size" form:"page_size,default=10"`
}

type SkuListResp struct {
	List     []SkuItem `json:"list"`
	Total    int64     `json:"total"`
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`
}

type AcquireTokenReq struct {
	ActivityId string `json:"activity_id" validate:"required"`
	SkuId      string `json:"sku_id" validate:"required"`
}

type AcquireTokenResp struct {
	Token string `json:"token"`
}

type SubmitOrderReq struct {
	ActivityId string `json:"activity_id" validate:"required"`
	SkuId      string `json:"sku_id" validate:"required"`
	Token      string `json:"token" validate:"required"`
	Quantity   int64  `json:"quantity" validate:"required,min=1"`
}

type SubmitOrderResp struct {
	OrderId string `json:"order_id"`
	Status  int32  `json:"status"`
}

type GetOrderReq struct {
	OrderId string `json:"order_id" path:"order_id"`
}

type GetOrderResp struct {
	OrderId     string `json:"order_id"`
	ActivityId  string `json:"activity_id"`
	SkuId       string `json:"sku_id"`
	Quantity    int64  `json:"quantity"`
	TotalAmount int64  `json:"total_amount"`
	Status      int32  `json:"status"`
	CreatedAt   string `json:"created_at"`
}

type MallProductItem struct {
	Id         string `json:"id"`
	SpuCode    string `json:"spu_code"`
	Name       string `json:"name"`
	CategoryId string `json:"category_id"`
	Brand      string `json:"brand"`
	Status     int32  `json:"status"`
	MainImage  string `json:"main_image"`
	Detail     string `json:"detail"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type MallSkuItem struct {
	Id        string `json:"id"`
	ProductId string `json:"product_id"`
	SkuCode   string `json:"sku_code"`
	Name      string `json:"name"`
	Specs     string `json:"specs"`
	Price     int64  `json:"price"`
	Stock     int64  `json:"stock"`
	Sold      int64  `json:"sold"`
	Status    int32  `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type MallProductListReq struct {
	Page       int    `json:"page" form:"page,default=1"`
	PageSize   int    `json:"page_size" form:"page_size,default=10"`
	CategoryId string `json:"category_id" form:"category_id"`
	Keyword    string `json:"keyword" form:"keyword"`
	Status     int32  `json:"status" form:"status,default=1"`
}

type MallProductListResp struct {
	List     []MallProductItem `json:"list"`
	Total    int64             `json:"total"`
	Page     int               `json:"page"`
	PageSize int               `json:"page_size"`
}

type MallProductDetailReq struct {
	Id string `json:"id" path:"id"`
}

type MallProductDetailResp struct {
	Product MallProductItem `json:"product"`
}

type MallSkuListReq struct {
	ProductId string `json:"product_id" form:"product_id,required"`
	Page      int    `json:"page" form:"page,default=1"`
	PageSize  int    `json:"page_size" form:"page_size,default=10"`
	Status    int32  `json:"status" form:"status,default=1"`
}

type MallSkuListResp struct {
	List     []MallSkuItem `json:"list"`
	Total    int64         `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
}

type MallOrderItem struct {
	ProductId   string `json:"product_id"`
	SkuId       string `json:"sku_id"`
	SkuName     string `json:"sku_name"`
	Price       int64  `json:"price"`
	Quantity    int64  `json:"quantity"`
	TotalAmount int64  `json:"total_amount"`
	Snapshot    string `json:"snapshot"`
}

type MallOrderResp struct {
	Id             string          `json:"id"`
	UserId         string          `json:"user_id"`
	TotalAmount    int64           `json:"total_amount"`
	Status         int32           `json:"status"`
	PayType        string          `json:"pay_type"`
	PayTime        string          `json:"pay_time"`
	Remark         string          `json:"remark"`
	Snapshot       string          `json:"snapshot"`
	IdempotencyKey string          `json:"idempotency_key"`
	Items          []MallOrderItem `json:"items"`
	CreatedAt      string          `json:"created_at"`
	UpdatedAt      string          `json:"updated_at"`
}

type MallCreateOrderReq struct {
	SkuId          string `json:"sku_id" validate:"required"`
	Quantity       int64  `json:"quantity" validate:"required,min=1,max=99"`
	Remark         string `json:"remark"`
	IdempotencyKey string `json:"idempotency_key" validate:"required"`
}

type MallCreateOrderResp struct {
	OrderId string `json:"order_id"`
	Status  int32  `json:"status"`
}

type MallOrderListReq struct {
	Page     int   `json:"page" form:"page,default=1"`
	PageSize int   `json:"page_size" form:"page_size,default=10"`
	Status   int32 `json:"status" form:"status,default=-1"`
}

type MallOrderListResp struct {
	List     []MallOrderResp `json:"list"`
	Total    int64           `json:"total"`
	Page     int             `json:"page"`
	PageSize int             `json:"page_size"`
}

type MallOrderDetailReq struct {
	Id string `json:"id" path:"id"`
}

type MallOrderDetailResp struct {
	Order MallOrderResp `json:"order"`
}

type MallCancelOrderReq struct {
	Id string `json:"id" path:"id"`
}

type AgentRecommendReq struct {
	Query       string `json:"query" validate:"required"`
	BudgetCents int64  `json:"budget_cents,optional"`
	MaxItems    int    `json:"max_items,optional"`
}

type AgentIntent struct {
	BudgetCents int64    `json:"budget_cents"`
	MaxItems    int32    `json:"max_items"`
	Keywords    []string `json:"keywords"`
	Preferences []string `json:"preferences"`
}

type AgentBundleItem struct {
	Id         string  `json:"id"`
	Name       string  `json:"name"`
	Category   string  `json:"category"`
	Source     string  `json:"source"`
	PriceCents int64   `json:"price_cents"`
	Stock      int64   `json:"stock"`
	Score      float64 `json:"score"`
	Reason     string  `json:"reason"`
}

type AgentToolCall struct {
	Name    string `json:"name"`
	Success bool   `json:"success"`
	Detail  string `json:"detail"`
}

type AgentRecommendResp struct {
	Intent          AgentIntent       `json:"intent"`
	Items           []AgentBundleItem `json:"items"`
	TotalPriceCents int64             `json:"total_price_cents"`
	Summary         string            `json:"summary"`
	ToolsUsed       []AgentToolCall   `json:"tools_used"`
}
