// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/rpc/payment/desc/payment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付流水
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                     // 流水ID
	OutTradeNo    string                 `protobuf:"bytes,2,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"` // 商户订单号（提交给支付宝）
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`            // 关联的业务订单ID
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // 用户ID
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`                            // 金额，单位：分
	Channel       string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`                           // 支付渠道，如 alipay
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                            // 状态，0:pending 1:success 2:closed
	TradeNo       string                 `protobuf:"bytes,8,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`            // 支付宝交易号
	BuyerId       string                 `protobuf:"bytes,9,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`            // 支付宝买家ID
	PaidAt        string                 `protobuf:"bytes,10,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`              // 支付完成时间
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_services_rpc_payment_desc_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Payment) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Payment) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *Payment) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *Payment) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 发起支付：根据订单创建一笔支付并返回支付宝二维码。
// 金额由网关从 mall 订单读取后传入（网关侧已校验订单归属与金额），payment-rpc 不直接依赖 mall。
type CreatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`  // 金额，单位：分
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"` // 可选，订单标题；为空时由服务端生成
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_payment_desc_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type CreatePaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`
	QrCode        string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"` // 支付宝二维码链接，前端据此渲染二维码
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResp) Reset() {
	*x = CreatePaymentResp{}
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResp) ProtoMessage() {}

func (x *CreatePaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResp.ProtoReflect.Descriptor instead.
func (*CreatePaymentResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_payment_desc_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentResp) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *CreatePaymentResp) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *CreatePaymentResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 查询支付结果（主动向支付宝查询并同步本地流水，本地兜底确认用）
type QueryPaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutTradeNo    string                 `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"` // 二选一
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentReq) Reset() {
	*x = QueryPaymentReq{}
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentReq) ProtoMessage() {}

func (x *QueryPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentReq.ProtoReflect.Descriptor instead.
func (*QueryPaymentReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_payment_desc_payment_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPaymentReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *QueryPaymentReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type QueryPaymentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0:pending 1:success 2:closed
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Payment       *Payment               `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentResp) Reset() {
	*x = QueryPaymentResp{}
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentResp) ProtoMessage() {}

func (x *QueryPaymentResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentResp.ProtoReflect.Descriptor instead.
func (*QueryPaymentResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_payment_desc_payment_proto_rawDescGZIP(), []int{4}
}

func (x *QueryPaymentResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryPaymentResp) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *QueryPaymentResp) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// 处理支付宝异步通知（由 REST 网关验签前的原始表单参数透传进来，服务端负责验签 + 幂等确认）
type HandleNotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleNotifyReq) Reset() {
	*x = HandleNotifyReq{}
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleNotifyReq) ProtoMessage() {}

func (x *HandleNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleNotifyReq.ProtoReflect.Descriptor instead.
func (*HandleNotifyReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_payment_desc_payment_proto_rawDescGZIP(), []int{5}
}

func (x *HandleNotifyReq) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type HandleNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleNotifyResp) Reset() {
	*x = HandleNotifyResp{}
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleNotifyResp) ProtoMessage() {}

func (x *HandleNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_payment_desc_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleNotifyResp.ProtoReflect.Descriptor instead.
func (*HandleNotifyResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_payment_desc_payment_proto_rawDescGZIP(), []int{6}
}

func (x *HandleNotifyResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HandleNotifyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_services_rpc_payment_desc_payment_proto protoreflect.FileDescriptor

const file_services_rpc_payment_desc_payment_proto_rawDesc = "" +
	"\n" +
	"'services/rpc/payment/desc/payment.proto\x12\apayment\"\xc6\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\fout_trade_no\x18\x02 \x01(\tR\n" +
	"outTradeNo\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x19\n" +
	"\btrade_no\x18\b \x01(\tR\atradeNo\x12\x19\n" +
	"\bbuyer_id\x18\t \x01(\tR\abuyerId\x12\x17\n" +
	"\apaid_at\x18\n" +
	" \x01(\tR\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"x\n" +
	"\x10CreatePaymentReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\"f\n" +
	"\x11CreatePaymentResp\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"N\n" +
	"\x0fQueryPaymentReq\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"q\n" +
	"\x10QueryPaymentResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12*\n" +
	"\apayment\x18\x03 \x01(\v2\x10.payment.PaymentR\apayment\"\x8a\x01\n" +
	"\x0fHandleNotifyReq\x12<\n" +
	"\x06params\x18\x01 \x03(\v2$.payment.HandleNotifyReq.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x10HandleNotifyResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe8\x01\n" +
	"\x0ePaymentService\x12H\n" +
	"\rCreatePayment\x12\x19.payment.CreatePaymentReq\x1a\x1a.payment.CreatePaymentResp\"\x00\x12E\n" +
	"\fQueryPayment\x12\x18.payment.QueryPaymentReq\x1a\x19.payment.QueryPaymentResp\"\x00\x12E\n" +
	"\fHandleNotify\x12\x18.payment.HandleNotifyReq\x1a\x19.payment.HandleNotifyResp\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_services_rpc_payment_desc_payment_proto_rawDescOnce sync.Once
	file_services_rpc_payment_desc_payment_proto_rawDescData []byte
)

func file_services_rpc_payment_desc_payment_proto_rawDescGZIP() []byte {
	file_services_rpc_payment_desc_payment_proto_rawDescOnce.Do(func() {
		file_services_rpc_payment_desc_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_rpc_payment_desc_payment_proto_rawDesc), len(file_services_rpc_payment_desc_payment_proto_rawDesc)))
	})
	return file_services_rpc_payment_desc_payment_proto_rawDescData
}

var file_services_rpc_payment_desc_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_services_rpc_payment_desc_payment_proto_goTypes = []any{
	(*Payment)(nil),           // 0: payment.Payment
	(*CreatePaymentReq)(nil),  // 1: payment.CreatePaymentReq
	(*CreatePaymentResp)(nil), // 2: payment.CreatePaymentResp
	(*QueryPaymentReq)(nil),   // 3: payment.QueryPaymentReq
	(*QueryPaymentResp)(nil),  // 4: payment.QueryPaymentResp
	(*HandleNotifyReq)(nil),   // 5: payment.HandleNotifyReq
	(*HandleNotifyResp)(nil),  // 6: payment.HandleNotifyResp
	nil,                       // 7: payment.HandleNotifyReq.ParamsEntry
}
var file_services_rpc_payment_desc_payment_proto_depIdxs = []int32{
	0, // 0: payment.QueryPaymentResp.payment:type_name -> payment.Payment
	7, // 1: payment.HandleNotifyReq.params:type_name -> payment.HandleNotifyReq.ParamsEntry
	1, // 2: payment.PaymentService.CreatePayment:input_type -> payment.CreatePaymentReq
	3, // 3: payment.PaymentService.QueryPayment:input_type -> payment.QueryPaymentReq
	5, // 4: payment.PaymentService.HandleNotify:input_type -> payment.HandleNotifyReq
	2, // 5: payment.PaymentService.CreatePayment:output_type -> payment.CreatePaymentResp
	4, // 6: payment.PaymentService.QueryPayment:output_type -> payment.QueryPaymentResp
	6, // 7: payment.PaymentService.HandleNotify:output_type -> payment.HandleNotifyResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_rpc_payment_desc_payment_proto_init() }
func file_services_rpc_payment_desc_payment_proto_init() {
	if File_services_rpc_payment_desc_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_rpc_payment_desc_payment_proto_rawDesc), len(file_services_rpc_payment_desc_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_rpc_payment_desc_payment_proto_goTypes,
		DependencyIndexes: file_services_rpc_payment_desc_payment_proto_depIdxs,
		MessageInfos:      file_services_rpc_payment_desc_payment_proto_msgTypes,
	}.Build()
	File_services_rpc_payment_desc_payment_proto = out.File
	file_services_rpc_payment_desc_payment_proto_goTypes = nil
	file_services_rpc_payment_desc_payment_proto_depIdxs = nil
}
