// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: agent.proto

package recommendservice

import (
	"context"

	"budgetmatch-sim/services/rpc/agent/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BundleItem                = pb.BundleItem
	ConversationSummary       = pb.ConversationSummary
	ConversationTurn          = pb.ConversationTurn
	DeleteConversationReq     = pb.DeleteConversationReq
	DeleteConversationResp    = pb.DeleteConversationResp
	DemandConflict            = pb.DemandConflict
	DemandState               = pb.DemandState
	Intent                    = pb.Intent
	ListConversationTurnsReq  = pb.ListConversationTurnsReq
	ListConversationTurnsResp = pb.ListConversationTurnsResp
	ListConversationsReq      = pb.ListConversationsReq
	ListConversationsResp     = pb.ListConversationsResp
	PlanDemandReq             = pb.PlanDemandReq
	PlanDemandResp            = pb.PlanDemandResp
	RecommendReq              = pb.RecommendReq
	RecommendResp             = pb.RecommendResp
	ToolCall                  = pb.ToolCall

	RecommendService interface {
		Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*RecommendResp, error)
		PlanDemand(ctx context.Context, in *PlanDemandReq, opts ...grpc.CallOption) (*PlanDemandResp, error)
		ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error)
		ListConversationTurns(ctx context.Context, in *ListConversationTurnsReq, opts ...grpc.CallOption) (*ListConversationTurnsResp, error)
		DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error)
	}

	defaultRecommendService struct {
		cli zrpc.Client
	}
)

func NewRecommendService(cli zrpc.Client) RecommendService {
	return &defaultRecommendService{
		cli: cli,
	}
}

func (m *defaultRecommendService) Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*RecommendResp, error) {
	client := pb.NewRecommendServiceClient(m.cli.Conn())
	return client.Recommend(ctx, in, opts...)
}

func (m *defaultRecommendService) PlanDemand(ctx context.Context, in *PlanDemandReq, opts ...grpc.CallOption) (*PlanDemandResp, error) {
	client := pb.NewRecommendServiceClient(m.cli.Conn())
	return client.PlanDemand(ctx, in, opts...)
}

func (m *defaultRecommendService) ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error) {
	client := pb.NewRecommendServiceClient(m.cli.Conn())
	return client.ListConversations(ctx, in, opts...)
}

func (m *defaultRecommendService) ListConversationTurns(ctx context.Context, in *ListConversationTurnsReq, opts ...grpc.CallOption) (*ListConversationTurnsResp, error) {
	client := pb.NewRecommendServiceClient(m.cli.Conn())
	return client.ListConversationTurns(ctx, in, opts...)
}

func (m *defaultRecommendService) DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error) {
	client := pb.NewRecommendServiceClient(m.cli.Conn())
	return client.DeleteConversation(ctx, in, opts...)
}
