// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: services/rpc/agent/proto/agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecommendService_Recommend_FullMethodName             = "/agent.RecommendService/Recommend"
	RecommendService_RecommendStream_FullMethodName       = "/agent.RecommendService/RecommendStream"
	RecommendService_PlanDemand_FullMethodName            = "/agent.RecommendService/PlanDemand"
	RecommendService_ExecuteDemand_FullMethodName         = "/agent.RecommendService/ExecuteDemand"
	RecommendService_ListConversations_FullMethodName     = "/agent.RecommendService/ListConversations"
	RecommendService_ListConversationTurns_FullMethodName = "/agent.RecommendService/ListConversationTurns"
	RecommendService_DeleteConversation_FullMethodName    = "/agent.RecommendService/DeleteConversation"
)

// RecommendServiceClient is the client API for RecommendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendServiceClient interface {
	Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*RecommendResp, error)
	// Requires a user JWT and transport deadline <= 30s. Replay emits final+done
	// only. Clients require final+done(ok=true)+OK EOF; EOF alone is not success.
	RecommendStream(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecommendStreamEvent], error)
	PlanDemand(ctx context.Context, in *PlanDemandReq, opts ...grpc.CallOption) (*PlanDemandResp, error)
	ExecuteDemand(ctx context.Context, in *ExecuteDemandReq, opts ...grpc.CallOption) (*RecommendResp, error)
	ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error)
	ListConversationTurns(ctx context.Context, in *ListConversationTurnsReq, opts ...grpc.CallOption) (*ListConversationTurnsResp, error)
	DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error)
}

type recommendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendServiceClient(cc grpc.ClientConnInterface) RecommendServiceClient {
	return &recommendServiceClient{cc}
}

func (c *recommendServiceClient) Recommend(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (*RecommendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResp)
	err := c.cc.Invoke(ctx, RecommendService_Recommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) RecommendStream(ctx context.Context, in *RecommendReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecommendStreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecommendService_ServiceDesc.Streams[0], RecommendService_RecommendStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecommendReq, RecommendStreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecommendService_RecommendStreamClient = grpc.ServerStreamingClient[RecommendStreamEvent]

func (c *recommendServiceClient) PlanDemand(ctx context.Context, in *PlanDemandReq, opts ...grpc.CallOption) (*PlanDemandResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanDemandResp)
	err := c.cc.Invoke(ctx, RecommendService_PlanDemand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) ExecuteDemand(ctx context.Context, in *ExecuteDemandReq, opts ...grpc.CallOption) (*RecommendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResp)
	err := c.cc.Invoke(ctx, RecommendService_ExecuteDemand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) ListConversations(ctx context.Context, in *ListConversationsReq, opts ...grpc.CallOption) (*ListConversationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResp)
	err := c.cc.Invoke(ctx, RecommendService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) ListConversationTurns(ctx context.Context, in *ListConversationTurnsReq, opts ...grpc.CallOption) (*ListConversationTurnsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationTurnsResp)
	err := c.cc.Invoke(ctx, RecommendService_ListConversationTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResp)
	err := c.cc.Invoke(ctx, RecommendService_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendServiceServer is the server API for RecommendService service.
// All implementations must embed UnimplementedRecommendServiceServer
// for forward compatibility.
type RecommendServiceServer interface {
	Recommend(context.Context, *RecommendReq) (*RecommendResp, error)
	// Requires a user JWT and transport deadline <= 30s. Replay emits final+done
	// only. Clients require final+done(ok=true)+OK EOF; EOF alone is not success.
	RecommendStream(*RecommendReq, grpc.ServerStreamingServer[RecommendStreamEvent]) error
	PlanDemand(context.Context, *PlanDemandReq) (*PlanDemandResp, error)
	ExecuteDemand(context.Context, *ExecuteDemandReq) (*RecommendResp, error)
	ListConversations(context.Context, *ListConversationsReq) (*ListConversationsResp, error)
	ListConversationTurns(context.Context, *ListConversationTurnsReq) (*ListConversationTurnsResp, error)
	DeleteConversation(context.Context, *DeleteConversationReq) (*DeleteConversationResp, error)
	mustEmbedUnimplementedRecommendServiceServer()
}

// UnimplementedRecommendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecommendServiceServer struct{}

func (UnimplementedRecommendServiceServer) Recommend(context.Context, *RecommendReq) (*RecommendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Recommend not implemented")
}
func (UnimplementedRecommendServiceServer) RecommendStream(*RecommendReq, grpc.ServerStreamingServer[RecommendStreamEvent]) error {
	return status.Error(codes.Unimplemented, "method RecommendStream not implemented")
}
func (UnimplementedRecommendServiceServer) PlanDemand(context.Context, *PlanDemandReq) (*PlanDemandResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanDemand not implemented")
}
func (UnimplementedRecommendServiceServer) ExecuteDemand(context.Context, *ExecuteDemandReq) (*RecommendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteDemand not implemented")
}
func (UnimplementedRecommendServiceServer) ListConversations(context.Context, *ListConversationsReq) (*ListConversationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedRecommendServiceServer) ListConversationTurns(context.Context, *ListConversationTurnsReq) (*ListConversationTurnsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversationTurns not implemented")
}
func (UnimplementedRecommendServiceServer) DeleteConversation(context.Context, *DeleteConversationReq) (*DeleteConversationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedRecommendServiceServer) mustEmbedUnimplementedRecommendServiceServer() {}
func (UnimplementedRecommendServiceServer) testEmbeddedByValue()                          {}

// UnsafeRecommendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendServiceServer will
// result in compilation errors.
type UnsafeRecommendServiceServer interface {
	mustEmbedUnimplementedRecommendServiceServer()
}

func RegisterRecommendServiceServer(s grpc.ServiceRegistrar, srv RecommendServiceServer) {
	// If the following call panics, it indicates UnimplementedRecommendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecommendService_ServiceDesc, srv)
}

func _RecommendService_Recommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).Recommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_Recommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).Recommend(ctx, req.(*RecommendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_RecommendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecommendReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecommendServiceServer).RecommendStream(m, &grpc.GenericServerStream[RecommendReq, RecommendStreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecommendService_RecommendStreamServer = grpc.ServerStreamingServer[RecommendStreamEvent]

func _RecommendService_PlanDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanDemandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).PlanDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_PlanDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).PlanDemand(ctx, req.(*PlanDemandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_ExecuteDemand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteDemandReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).ExecuteDemand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_ExecuteDemand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).ExecuteDemand(ctx, req.(*ExecuteDemandReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).ListConversations(ctx, req.(*ListConversationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_ListConversationTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationTurnsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).ListConversationTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_ListConversationTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).ListConversationTurns(ctx, req.(*ListConversationTurnsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).DeleteConversation(ctx, req.(*DeleteConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendService_ServiceDesc is the grpc.ServiceDesc for RecommendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.RecommendService",
	HandlerType: (*RecommendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recommend",
			Handler:    _RecommendService_Recommend_Handler,
		},
		{
			MethodName: "PlanDemand",
			Handler:    _RecommendService_PlanDemand_Handler,
		},
		{
			MethodName: "ExecuteDemand",
			Handler:    _RecommendService_ExecuteDemand_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _RecommendService_ListConversations_Handler,
		},
		{
			MethodName: "ListConversationTurns",
			Handler:    _RecommendService_ListConversationTurns_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _RecommendService_DeleteConversation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecommendStream",
			Handler:       _RecommendService_RecommendStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/rpc/agent/proto/agent.proto",
}
