// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: services/rpc/agent/proto/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	BudgetCents    int64                  `protobuf:"varint,2,opt,name=budget_cents,json=budgetCents,proto3" json:"budget_cents,omitempty"`
	MaxItems       int32                  `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	ConversationId string                 `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // 多轮对话会话 ID，为空时由服务端生成并在响应中回传
	TurnId         string                 `protobuf:"bytes,6,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`                         // 客户端生成的轮次幂等 ID，为空时由服务端生成
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecommendReq) Reset() {
	*x = RecommendReq{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendReq) ProtoMessage() {}

func (x *RecommendReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendReq.ProtoReflect.Descriptor instead.
func (*RecommendReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecommendReq) GetBudgetCents() int64 {
	if x != nil {
		return x.BudgetCents
	}
	return 0
}

func (x *RecommendReq) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *RecommendReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RecommendReq) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

type Intent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BudgetCents   int64                  `protobuf:"varint,1,opt,name=budget_cents,json=budgetCents,proto3" json:"budget_cents,omitempty"`
	MaxItems      int32                  `protobuf:"varint,2,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Preferences   []string               `protobuf:"bytes,4,rep,name=preferences,proto3" json:"preferences,omitempty"`
	Demand        *DemandState           `protobuf:"bytes,5,opt,name=demand,proto3" json:"demand,omitempty"` // absent for legacy recommendation turns
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Intent) GetBudgetCents() int64 {
	if x != nil {
		return x.BudgetCents
	}
	return 0
}

func (x *Intent) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *Intent) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Intent) GetPreferences() []string {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *Intent) GetDemand() *DemandState {
	if x != nil {
		return x.Demand
	}
	return nil
}

type DemandState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Required      []string               `protobuf:"bytes,2,rep,name=required,proto3" json:"required,omitempty"`
	Optional      []string               `protobuf:"bytes,3,rep,name=optional,proto3" json:"optional,omitempty"`
	Excluded      []string               `protobuf:"bytes,4,rep,name=excluded,proto3" json:"excluded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandState) Reset() {
	*x = DemandState{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandState) ProtoMessage() {}

func (x *DemandState) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandState.ProtoReflect.Descriptor instead.
func (*DemandState) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DemandState) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *DemandState) GetRequired() []string {
	if x != nil {
		return x.Required
	}
	return nil
}

func (x *DemandState) GetOptional() []string {
	if x != nil {
		return x.Optional
	}
	return nil
}

func (x *DemandState) GetExcluded() []string {
	if x != nil {
		return x.Excluded
	}
	return nil
}

type DemandConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandConflict) Reset() {
	*x = DemandConflict{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandConflict) ProtoMessage() {}

func (x *DemandConflict) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandConflict.ProtoReflect.Descriptor instead.
func (*DemandConflict) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DemandConflict) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DemandConflict) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

// Planning only: explicit, strict JSON patch; no model or product execution.
type PlanDemandReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	BudgetCents    int64                  `protobuf:"varint,2,opt,name=budget_cents,json=budgetCents,proto3" json:"budget_cents,omitempty"`
	MaxItems       int32                  `protobuf:"varint,3,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	TurnId         string                 `protobuf:"bytes,5,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	DemandPatch    string                 `protobuf:"bytes,6,opt,name=demand_patch,json=demandPatch,proto3" json:"demand_patch,omitempty"` // max 8192 bytes; empty inherits/initializes
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanDemandReq) Reset() {
	*x = PlanDemandReq{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanDemandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanDemandReq) ProtoMessage() {}

func (x *PlanDemandReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanDemandReq.ProtoReflect.Descriptor instead.
func (*PlanDemandReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PlanDemandReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PlanDemandReq) GetBudgetCents() int64 {
	if x != nil {
		return x.BudgetCents
	}
	return 0
}

func (x *PlanDemandReq) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *PlanDemandReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PlanDemandReq) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *PlanDemandReq) GetDemandPatch() string {
	if x != nil {
		return x.DemandPatch
	}
	return ""
}

type PlanDemandResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Intent            *Intent                `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // intent_ready / needs_clarification, never recommendation success
	Conflicts         []*DemandConflict      `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	ConversationId    string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationTitle string                 `protobuf:"bytes,5,opt,name=conversation_title,json=conversationTitle,proto3" json:"conversation_title,omitempty"`
	TurnId            string                 `protobuf:"bytes,6,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanDemandResp) Reset() {
	*x = PlanDemandResp{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanDemandResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanDemandResp) ProtoMessage() {}

func (x *PlanDemandResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanDemandResp.ProtoReflect.Descriptor instead.
func (*PlanDemandResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PlanDemandResp) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *PlanDemandResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlanDemandResp) GetConflicts() []*DemandConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *PlanDemandResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PlanDemandResp) GetConversationTitle() string {
	if x != nil {
		return x.ConversationTitle
	}
	return ""
}

func (x *PlanDemandResp) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

type BundleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	PriceCents    int64                  `protobuf:"varint,5,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleItem) Reset() {
	*x = BundleItem{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleItem) ProtoMessage() {}

func (x *BundleItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleItem.ProtoReflect.Descriptor instead.
func (*BundleItem) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *BundleItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BundleItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BundleItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BundleItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BundleItem) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *BundleItem) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *BundleItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BundleItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolCall) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type RecommendResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Intent            *Intent                `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	Items             []*BundleItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalPriceCents   int64                  `protobuf:"varint,3,opt,name=total_price_cents,json=totalPriceCents,proto3" json:"total_price_cents,omitempty"`
	Summary           string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	ToolsUsed         []*ToolCall            `protobuf:"bytes,5,rep,name=tools_used,json=toolsUsed,proto3" json:"tools_used,omitempty"`
	ConversationId    string                 `protobuf:"bytes,6,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`          // 本次对话的会话 ID，客户端携带它发起下一轮
	ConversationTitle string                 `protobuf:"bytes,7,opt,name=conversation_title,json=conversationTitle,proto3" json:"conversation_title,omitempty"` // 会话稳定展示标题
	TurnId            string                 `protobuf:"bytes,8,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`                                  // 本轮幂等 ID
	Status            string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                                // nonempty for planning-only history results
	DemandConflicts   []*DemandConflict      `protobuf:"bytes,10,rep,name=demand_conflicts,json=demandConflicts,proto3" json:"demand_conflicts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecommendResp) Reset() {
	*x = RecommendResp{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResp) ProtoMessage() {}

func (x *RecommendResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResp.ProtoReflect.Descriptor instead.
func (*RecommendResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RecommendResp) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *RecommendResp) GetItems() []*BundleItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RecommendResp) GetTotalPriceCents() int64 {
	if x != nil {
		return x.TotalPriceCents
	}
	return 0
}

func (x *RecommendResp) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RecommendResp) GetToolsUsed() []*ToolCall {
	if x != nil {
		return x.ToolsUsed
	}
	return nil
}

func (x *RecommendResp) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RecommendResp) GetConversationTitle() string {
	if x != nil {
		return x.ConversationTitle
	}
	return ""
}

func (x *RecommendResp) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *RecommendResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecommendResp) GetDemandConflicts() []*DemandConflict {
	if x != nil {
		return x.DemandConflicts
	}
	return nil
}

type ConversationSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConversationId    string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationTitle string                 `protobuf:"bytes,2,opt,name=conversation_title,json=conversationTitle,proto3" json:"conversation_title,omitempty"`
	State             *Intent                `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	TurnCount         int64                  `protobuf:"varint,4,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	CreatedAtMs       int64                  `protobuf:"varint,5,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	UpdatedAtMs       int64                  `protobuf:"varint,6,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationSummary) Reset() {
	*x = ConversationSummary{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSummary) ProtoMessage() {}

func (x *ConversationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSummary.ProtoReflect.Descriptor instead.
func (*ConversationSummary) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ConversationSummary) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationSummary) GetConversationTitle() string {
	if x != nil {
		return x.ConversationTitle
	}
	return ""
}

func (x *ConversationSummary) GetState() *Intent {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ConversationSummary) GetTurnCount() int64 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *ConversationSummary) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *ConversationSummary) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

type ConversationTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnId        string                 `protobuf:"bytes,1,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	BudgetCents   int64                  `protobuf:"varint,4,opt,name=budget_cents,json=budgetCents,proto3" json:"budget_cents,omitempty"`
	MaxItems      int32                  `protobuf:"varint,5,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	Intent        *Intent                `protobuf:"bytes,6,opt,name=intent,proto3" json:"intent,omitempty"`
	Result        *RecommendResp         `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	CreatedAtMs   int64                  `protobuf:"varint,8,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	CompletedAtMs int64                  `protobuf:"varint,9,opt,name=completed_at_ms,json=completedAtMs,proto3" json:"completed_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationTurn) Reset() {
	*x = ConversationTurn{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurn) ProtoMessage() {}

func (x *ConversationTurn) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurn.ProtoReflect.Descriptor instead.
func (*ConversationTurn) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ConversationTurn) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *ConversationTurn) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ConversationTurn) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ConversationTurn) GetBudgetCents() int64 {
	if x != nil {
		return x.BudgetCents
	}
	return 0
}

func (x *ConversationTurn) GetMaxItems() int32 {
	if x != nil {
		return x.MaxItems
	}
	return 0
}

func (x *ConversationTurn) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *ConversationTurn) GetResult() *RecommendResp {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ConversationTurn) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *ConversationTurn) GetCompletedAtMs() int64 {
	if x != nil {
		return x.CompletedAtMs
	}
	return 0
}

type ListConversationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 从 1 开始
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 1-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsReq) Reset() {
	*x = ListConversationsReq{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsReq) ProtoMessage() {}

func (x *ListConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsReq.ProtoReflect.Descriptor instead.
func (*ListConversationsReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListConversationsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListConversationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ConversationSummary `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResp) Reset() {
	*x = ListConversationsResp{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResp) ProtoMessage() {}

func (x *ListConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResp.ProtoReflect.Descriptor instead.
func (*ListConversationsResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListConversationsResp) GetList() []*ConversationSummary {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListConversationsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConversationsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListConversationTurnsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 从 1 开始
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 1-100
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConversationTurnsReq) Reset() {
	*x = ListConversationTurnsReq{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationTurnsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationTurnsReq) ProtoMessage() {}

func (x *ListConversationTurnsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationTurnsReq.ProtoReflect.Descriptor instead.
func (*ListConversationTurnsReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ListConversationTurnsReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListConversationTurnsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationTurnsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListConversationTurnsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *ConversationSummary   `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	List          []*ConversationTurn    `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationTurnsResp) Reset() {
	*x = ListConversationTurnsResp{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationTurnsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationTurnsResp) ProtoMessage() {}

func (x *ListConversationTurnsResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationTurnsResp.ProtoReflect.Descriptor instead.
func (*ListConversationTurnsResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ListConversationTurnsResp) GetConversation() *ConversationSummary {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *ListConversationTurnsResp) GetList() []*ConversationTurn {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListConversationTurnsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationTurnsResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConversationTurnsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteConversationReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteConversationReq) Reset() {
	*x = DeleteConversationReq{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationReq) ProtoMessage() {}

func (x *DeleteConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationReq.ProtoReflect.Descriptor instead.
func (*DeleteConversationReq) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteConversationReq) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResp) Reset() {
	*x = DeleteConversationResp{}
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResp) ProtoMessage() {}

func (x *DeleteConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_rpc_agent_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResp.ProtoReflect.Descriptor instead.
func (*DeleteConversationResp) Descriptor() ([]byte, []int) {
	return file_services_rpc_agent_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteConversationResp) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_services_rpc_agent_proto_agent_proto protoreflect.FileDescriptor

const file_services_rpc_agent_proto_agent_proto_rawDesc = "" +
	"\n" +
	"$services/rpc/agent/proto/agent.proto\x12\x05agent\"\xb5\x01\n" +
	"\fRecommendReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fbudget_cents\x18\x02 \x01(\x03R\vbudgetCents\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\x05R\bmaxItems\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aturn_id\x18\x06 \x01(\tR\x06turnIdJ\x04\b\x04\x10\x05R\auser_id\"\xb2\x01\n" +
	"\x06Intent\x12!\n" +
	"\fbudget_cents\x18\x01 \x01(\x03R\vbudgetCents\x12\x1b\n" +
	"\tmax_items\x18\x02 \x01(\x05R\bmaxItems\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12 \n" +
	"\vpreferences\x18\x04 \x03(\tR\vpreferences\x12*\n" +
	"\x06demand\x18\x05 \x01(\v2\x12.agent.DemandStateR\x06demand\"\x88\x01\n" +
	"\vDemandState\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x1a\n" +
	"\brequired\x18\x02 \x03(\tR\brequired\x12\x1a\n" +
	"\boptional\x18\x03 \x03(\tR\boptional\x12\x1a\n" +
	"\bexcluded\x18\x04 \x03(\tR\bexcluded\"@\n" +
	"\x0eDemandConflict\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\xca\x01\n" +
	"\rPlanDemandReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fbudget_cents\x18\x02 \x01(\x03R\vbudgetCents\x12\x1b\n" +
	"\tmax_items\x18\x03 \x01(\x05R\bmaxItems\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12\x17\n" +
	"\aturn_id\x18\x05 \x01(\tR\x06turnId\x12!\n" +
	"\fdemand_patch\x18\x06 \x01(\tR\vdemandPatch\"\xf5\x01\n" +
	"\x0ePlanDemandResp\x12%\n" +
	"\x06intent\x18\x01 \x01(\v2\r.agent.IntentR\x06intent\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x123\n" +
	"\tconflicts\x18\x03 \x03(\v2\x15.agent.DemandConflictR\tconflicts\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12-\n" +
	"\x12conversation_title\x18\x05 \x01(\tR\x11conversationTitle\x12\x17\n" +
	"\aturn_id\x18\x06 \x01(\tR\x06turnId\"\xc9\x01\n" +
	"\n" +
	"BundleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vprice_cents\x18\x05 \x01(\x03R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x03R\x05stock\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"P\n" +
	"\bToolCall\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xa0\x03\n" +
	"\rRecommendResp\x12%\n" +
	"\x06intent\x18\x01 \x01(\v2\r.agent.IntentR\x06intent\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.agent.BundleItemR\x05items\x12*\n" +
	"\x11total_price_cents\x18\x03 \x01(\x03R\x0ftotalPriceCents\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12.\n" +
	"\n" +
	"tools_used\x18\x05 \x03(\v2\x0f.agent.ToolCallR\ttoolsUsed\x12'\n" +
	"\x0fconversation_id\x18\x06 \x01(\tR\x0econversationId\x12-\n" +
	"\x12conversation_title\x18\a \x01(\tR\x11conversationTitle\x12\x17\n" +
	"\aturn_id\x18\b \x01(\tR\x06turnId\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12@\n" +
	"\x10demand_conflicts\x18\n" +
	" \x03(\v2\x15.agent.DemandConflictR\x0fdemandConflicts\"\xf9\x01\n" +
	"\x13ConversationSummary\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12-\n" +
	"\x12conversation_title\x18\x02 \x01(\tR\x11conversationTitle\x12#\n" +
	"\x05state\x18\x03 \x01(\v2\r.agent.IntentR\x05state\x12\x1d\n" +
	"\n" +
	"turn_count\x18\x04 \x01(\x03R\tturnCount\x12\"\n" +
	"\rcreated_at_ms\x18\x05 \x01(\x03R\vcreatedAtMs\x12\"\n" +
	"\rupdated_at_ms\x18\x06 \x01(\x03R\vupdatedAtMs\"\xbe\x02\n" +
	"\x10ConversationTurn\x12\x17\n" +
	"\aturn_id\x18\x01 \x01(\tR\x06turnId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12!\n" +
	"\fbudget_cents\x18\x04 \x01(\x03R\vbudgetCents\x12\x1b\n" +
	"\tmax_items\x18\x05 \x01(\x05R\bmaxItems\x12%\n" +
	"\x06intent\x18\x06 \x01(\v2\r.agent.IntentR\x06intent\x12,\n" +
	"\x06result\x18\a \x01(\v2\x14.agent.RecommendRespR\x06result\x12\"\n" +
	"\rcreated_at_ms\x18\b \x01(\x03R\vcreatedAtMs\x12&\n" +
	"\x0fcompleted_at_ms\x18\t \x01(\x03R\rcompletedAtMs\"G\n" +
	"\x14ListConversationsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8e\x01\n" +
	"\x15ListConversationsResp\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.agent.ConversationSummaryR\x04list\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"t\n" +
	"\x18ListConversationTurnsReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xcf\x01\n" +
	"\x19ListConversationTurnsResp\x12>\n" +
	"\fconversation\x18\x01 \x01(\v2\x1a.agent.ConversationSummaryR\fconversation\x12+\n" +
	"\x04list\x18\x02 \x03(\v2\x17.agent.ConversationTurnR\x04list\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\"@\n" +
	"\x15DeleteConversationReq\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"2\n" +
	"\x16DeleteConversationResp\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\x8e\x03\n" +
	"\x10RecommendService\x128\n" +
	"\tRecommend\x12\x13.agent.RecommendReq\x1a\x14.agent.RecommendResp\"\x00\x12;\n" +
	"\n" +
	"PlanDemand\x12\x14.agent.PlanDemandReq\x1a\x15.agent.PlanDemandResp\"\x00\x12P\n" +
	"\x11ListConversations\x12\x1b.agent.ListConversationsReq\x1a\x1c.agent.ListConversationsResp\"\x00\x12\\\n" +
	"\x15ListConversationTurns\x12\x1f.agent.ListConversationTurnsReq\x1a .agent.ListConversationTurnsResp\"\x00\x12S\n" +
	"\x12DeleteConversation\x12\x1c.agent.DeleteConversationReq\x1a\x1d.agent.DeleteConversationResp\"\x00B\x06Z\x04./pbb\x06proto3"

var (
	file_services_rpc_agent_proto_agent_proto_rawDescOnce sync.Once
	file_services_rpc_agent_proto_agent_proto_rawDescData []byte
)

func file_services_rpc_agent_proto_agent_proto_rawDescGZIP() []byte {
	file_services_rpc_agent_proto_agent_proto_rawDescOnce.Do(func() {
		file_services_rpc_agent_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_rpc_agent_proto_agent_proto_rawDesc), len(file_services_rpc_agent_proto_agent_proto_rawDesc)))
	})
	return file_services_rpc_agent_proto_agent_proto_rawDescData
}

var file_services_rpc_agent_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_services_rpc_agent_proto_agent_proto_goTypes = []any{
	(*RecommendReq)(nil),              // 0: agent.RecommendReq
	(*Intent)(nil),                    // 1: agent.Intent
	(*DemandState)(nil),               // 2: agent.DemandState
	(*DemandConflict)(nil),            // 3: agent.DemandConflict
	(*PlanDemandReq)(nil),             // 4: agent.PlanDemandReq
	(*PlanDemandResp)(nil),            // 5: agent.PlanDemandResp
	(*BundleItem)(nil),                // 6: agent.BundleItem
	(*ToolCall)(nil),                  // 7: agent.ToolCall
	(*RecommendResp)(nil),             // 8: agent.RecommendResp
	(*ConversationSummary)(nil),       // 9: agent.ConversationSummary
	(*ConversationTurn)(nil),          // 10: agent.ConversationTurn
	(*ListConversationsReq)(nil),      // 11: agent.ListConversationsReq
	(*ListConversationsResp)(nil),     // 12: agent.ListConversationsResp
	(*ListConversationTurnsReq)(nil),  // 13: agent.ListConversationTurnsReq
	(*ListConversationTurnsResp)(nil), // 14: agent.ListConversationTurnsResp
	(*DeleteConversationReq)(nil),     // 15: agent.DeleteConversationReq
	(*DeleteConversationResp)(nil),    // 16: agent.DeleteConversationResp
}
var file_services_rpc_agent_proto_agent_proto_depIdxs = []int32{
	2,  // 0: agent.Intent.demand:type_name -> agent.DemandState
	1,  // 1: agent.PlanDemandResp.intent:type_name -> agent.Intent
	3,  // 2: agent.PlanDemandResp.conflicts:type_name -> agent.DemandConflict
	1,  // 3: agent.RecommendResp.intent:type_name -> agent.Intent
	6,  // 4: agent.RecommendResp.items:type_name -> agent.BundleItem
	7,  // 5: agent.RecommendResp.tools_used:type_name -> agent.ToolCall
	3,  // 6: agent.RecommendResp.demand_conflicts:type_name -> agent.DemandConflict
	1,  // 7: agent.ConversationSummary.state:type_name -> agent.Intent
	1,  // 8: agent.ConversationTurn.intent:type_name -> agent.Intent
	8,  // 9: agent.ConversationTurn.result:type_name -> agent.RecommendResp
	9,  // 10: agent.ListConversationsResp.list:type_name -> agent.ConversationSummary
	9,  // 11: agent.ListConversationTurnsResp.conversation:type_name -> agent.ConversationSummary
	10, // 12: agent.ListConversationTurnsResp.list:type_name -> agent.ConversationTurn
	0,  // 13: agent.RecommendService.Recommend:input_type -> agent.RecommendReq
	4,  // 14: agent.RecommendService.PlanDemand:input_type -> agent.PlanDemandReq
	11, // 15: agent.RecommendService.ListConversations:input_type -> agent.ListConversationsReq
	13, // 16: agent.RecommendService.ListConversationTurns:input_type -> agent.ListConversationTurnsReq
	15, // 17: agent.RecommendService.DeleteConversation:input_type -> agent.DeleteConversationReq
	8,  // 18: agent.RecommendService.Recommend:output_type -> agent.RecommendResp
	5,  // 19: agent.RecommendService.PlanDemand:output_type -> agent.PlanDemandResp
	12, // 20: agent.RecommendService.ListConversations:output_type -> agent.ListConversationsResp
	14, // 21: agent.RecommendService.ListConversationTurns:output_type -> agent.ListConversationTurnsResp
	16, // 22: agent.RecommendService.DeleteConversation:output_type -> agent.DeleteConversationResp
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_services_rpc_agent_proto_agent_proto_init() }
func file_services_rpc_agent_proto_agent_proto_init() {
	if File_services_rpc_agent_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_rpc_agent_proto_agent_proto_rawDesc), len(file_services_rpc_agent_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_rpc_agent_proto_agent_proto_goTypes,
		DependencyIndexes: file_services_rpc_agent_proto_agent_proto_depIdxs,
		MessageInfos:      file_services_rpc_agent_proto_agent_proto_msgTypes,
	}.Build()
	File_services_rpc_agent_proto_agent_proto = out.File
	file_services_rpc_agent_proto_agent_proto_goTypes = nil
	file_services_rpc_agent_proto_agent_proto_depIdxs = nil
}
