// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ActivityServiceClient is the client API for ActivityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityServiceClient interface {
	CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error)
	UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*UpdateActivityResp, error)
	GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error)
	ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error)
	DeleteActivity(ctx context.Context, in *DeleteActivityReq, opts ...grpc.CallOption) (*DeleteActivityResp, error)
	PreheatActivity(ctx context.Context, in *PreheatActivityReq, opts ...grpc.CallOption) (*PreheatActivityResp, error)
	OnlineActivity(ctx context.Context, in *OnlineActivityReq, opts ...grpc.CallOption) (*OnlineActivityResp, error)
	OfflineActivity(ctx context.Context, in *OfflineActivityReq, opts ...grpc.CallOption) (*OfflineActivityResp, error)
}

type activityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityServiceClient(cc grpc.ClientConnInterface) ActivityServiceClient {
	return &activityServiceClient{cc}
}

func (c *activityServiceClient) CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error) {
	out := new(CreateActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/CreateActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*UpdateActivityResp, error) {
	out := new(UpdateActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/UpdateActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error) {
	out := new(GetActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/GetActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error) {
	out := new(ListActivitiesResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/ListActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) DeleteActivity(ctx context.Context, in *DeleteActivityReq, opts ...grpc.CallOption) (*DeleteActivityResp, error) {
	out := new(DeleteActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/DeleteActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) PreheatActivity(ctx context.Context, in *PreheatActivityReq, opts ...grpc.CallOption) (*PreheatActivityResp, error) {
	out := new(PreheatActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/PreheatActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) OnlineActivity(ctx context.Context, in *OnlineActivityReq, opts ...grpc.CallOption) (*OnlineActivityResp, error) {
	out := new(OnlineActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/OnlineActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) OfflineActivity(ctx context.Context, in *OfflineActivityReq, opts ...grpc.CallOption) (*OfflineActivityResp, error) {
	out := new(OfflineActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.ActivityService/OfflineActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServiceServer is the server API for ActivityService service.
// All implementations must embed UnimplementedActivityServiceServer
// for forward compatibility
type ActivityServiceServer interface {
	CreateActivity(context.Context, *CreateActivityReq) (*CreateActivityResp, error)
	UpdateActivity(context.Context, *UpdateActivityReq) (*UpdateActivityResp, error)
	GetActivity(context.Context, *GetActivityReq) (*GetActivityResp, error)
	ListActivities(context.Context, *ListActivitiesReq) (*ListActivitiesResp, error)
	DeleteActivity(context.Context, *DeleteActivityReq) (*DeleteActivityResp, error)
	PreheatActivity(context.Context, *PreheatActivityReq) (*PreheatActivityResp, error)
	OnlineActivity(context.Context, *OnlineActivityReq) (*OnlineActivityResp, error)
	OfflineActivity(context.Context, *OfflineActivityReq) (*OfflineActivityResp, error)
	mustEmbedUnimplementedActivityServiceServer()
}

// UnimplementedActivityServiceServer must be embedded to have forward compatible implementations.
type UnimplementedActivityServiceServer struct {
}

func (UnimplementedActivityServiceServer) CreateActivity(context.Context, *CreateActivityReq) (*CreateActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedActivityServiceServer) UpdateActivity(context.Context, *UpdateActivityReq) (*UpdateActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActivity not implemented")
}
func (UnimplementedActivityServiceServer) GetActivity(context.Context, *GetActivityReq) (*GetActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedActivityServiceServer) ListActivities(context.Context, *ListActivitiesReq) (*ListActivitiesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedActivityServiceServer) DeleteActivity(context.Context, *DeleteActivityReq) (*DeleteActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteActivity not implemented")
}
func (UnimplementedActivityServiceServer) PreheatActivity(context.Context, *PreheatActivityReq) (*PreheatActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreheatActivity not implemented")
}
func (UnimplementedActivityServiceServer) OnlineActivity(context.Context, *OnlineActivityReq) (*OnlineActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnlineActivity not implemented")
}
func (UnimplementedActivityServiceServer) OfflineActivity(context.Context, *OfflineActivityReq) (*OfflineActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfflineActivity not implemented")
}
func (UnimplementedActivityServiceServer) mustEmbedUnimplementedActivityServiceServer() {}

// UnsafeActivityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServiceServer will
// result in compilation errors.
type UnsafeActivityServiceServer interface {
	mustEmbedUnimplementedActivityServiceServer()
}

func RegisterActivityServiceServer(s *grpc.Server, srv ActivityServiceServer) {
	s.RegisterService(&_ActivityService_serviceDesc, srv)
}

func _ActivityService_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/CreateActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).CreateActivity(ctx, req.(*CreateActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_UpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).UpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/UpdateActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).UpdateActivity(ctx, req.(*UpdateActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/GetActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).GetActivity(ctx, req.(*GetActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/ListActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).ListActivities(ctx, req.(*ListActivitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_DeleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).DeleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/DeleteActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).DeleteActivity(ctx, req.(*DeleteActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_PreheatActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreheatActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).PreheatActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/PreheatActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).PreheatActivity(ctx, req.(*PreheatActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_OnlineActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).OnlineActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/OnlineActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).OnlineActivity(ctx, req.(*OnlineActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_OfflineActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfflineActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).OfflineActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.ActivityService/OfflineActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).OfflineActivity(ctx, req.(*OfflineActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActivityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.ActivityService",
	HandlerType: (*ActivityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateActivity",
			Handler:    _ActivityService_CreateActivity_Handler,
		},
		{
			MethodName: "UpdateActivity",
			Handler:    _ActivityService_UpdateActivity_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _ActivityService_GetActivity_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _ActivityService_ListActivities_Handler,
		},
		{
			MethodName: "DeleteActivity",
			Handler:    _ActivityService_DeleteActivity_Handler,
		},
		{
			MethodName: "PreheatActivity",
			Handler:    _ActivityService_PreheatActivity_Handler,
		},
		{
			MethodName: "OnlineActivity",
			Handler:    _ActivityService_OnlineActivity_Handler,
		},
		{
			MethodName: "OfflineActivity",
			Handler:    _ActivityService_OfflineActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/rpc/seckill/proto/seckill.proto",
}

// SkuServiceClient is the client API for SkuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkuServiceClient interface {
	CreateSku(ctx context.Context, in *CreateSkuReq, opts ...grpc.CallOption) (*CreateSkuResp, error)
	UpdateSku(ctx context.Context, in *UpdateSkuReq, opts ...grpc.CallOption) (*UpdateSkuResp, error)
	GetSku(ctx context.Context, in *GetSkuReq, opts ...grpc.CallOption) (*GetSkuResp, error)
	ListSkusByActivity(ctx context.Context, in *ListSkusByActivityReq, opts ...grpc.CallOption) (*ListSkusByActivityResp, error)
	DeleteSku(ctx context.Context, in *DeleteSkuReq, opts ...grpc.CallOption) (*DeleteSkuResp, error)
}

type skuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkuServiceClient(cc grpc.ClientConnInterface) SkuServiceClient {
	return &skuServiceClient{cc}
}

func (c *skuServiceClient) CreateSku(ctx context.Context, in *CreateSkuReq, opts ...grpc.CallOption) (*CreateSkuResp, error) {
	out := new(CreateSkuResp)
	err := c.cc.Invoke(ctx, "/seckill.SkuService/CreateSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuServiceClient) UpdateSku(ctx context.Context, in *UpdateSkuReq, opts ...grpc.CallOption) (*UpdateSkuResp, error) {
	out := new(UpdateSkuResp)
	err := c.cc.Invoke(ctx, "/seckill.SkuService/UpdateSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuServiceClient) GetSku(ctx context.Context, in *GetSkuReq, opts ...grpc.CallOption) (*GetSkuResp, error) {
	out := new(GetSkuResp)
	err := c.cc.Invoke(ctx, "/seckill.SkuService/GetSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuServiceClient) ListSkusByActivity(ctx context.Context, in *ListSkusByActivityReq, opts ...grpc.CallOption) (*ListSkusByActivityResp, error) {
	out := new(ListSkusByActivityResp)
	err := c.cc.Invoke(ctx, "/seckill.SkuService/ListSkusByActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skuServiceClient) DeleteSku(ctx context.Context, in *DeleteSkuReq, opts ...grpc.CallOption) (*DeleteSkuResp, error) {
	out := new(DeleteSkuResp)
	err := c.cc.Invoke(ctx, "/seckill.SkuService/DeleteSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkuServiceServer is the server API for SkuService service.
// All implementations must embed UnimplementedSkuServiceServer
// for forward compatibility
type SkuServiceServer interface {
	CreateSku(context.Context, *CreateSkuReq) (*CreateSkuResp, error)
	UpdateSku(context.Context, *UpdateSkuReq) (*UpdateSkuResp, error)
	GetSku(context.Context, *GetSkuReq) (*GetSkuResp, error)
	ListSkusByActivity(context.Context, *ListSkusByActivityReq) (*ListSkusByActivityResp, error)
	DeleteSku(context.Context, *DeleteSkuReq) (*DeleteSkuResp, error)
	mustEmbedUnimplementedSkuServiceServer()
}

// UnimplementedSkuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkuServiceServer struct {
}

func (UnimplementedSkuServiceServer) CreateSku(context.Context, *CreateSkuReq) (*CreateSkuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSku not implemented")
}
func (UnimplementedSkuServiceServer) UpdateSku(context.Context, *UpdateSkuReq) (*UpdateSkuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSku not implemented")
}
func (UnimplementedSkuServiceServer) GetSku(context.Context, *GetSkuReq) (*GetSkuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSku not implemented")
}
func (UnimplementedSkuServiceServer) ListSkusByActivity(context.Context, *ListSkusByActivityReq) (*ListSkusByActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSkusByActivity not implemented")
}
func (UnimplementedSkuServiceServer) DeleteSku(context.Context, *DeleteSkuReq) (*DeleteSkuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSku not implemented")
}
func (UnimplementedSkuServiceServer) mustEmbedUnimplementedSkuServiceServer() {}

// UnsafeSkuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkuServiceServer will
// result in compilation errors.
type UnsafeSkuServiceServer interface {
	mustEmbedUnimplementedSkuServiceServer()
}

func RegisterSkuServiceServer(s *grpc.Server, srv SkuServiceServer) {
	s.RegisterService(&_SkuService_serviceDesc, srv)
}

func _SkuService_CreateSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).CreateSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SkuService/CreateSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).CreateSku(ctx, req.(*CreateSkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuService_UpdateSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).UpdateSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SkuService/UpdateSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).UpdateSku(ctx, req.(*UpdateSkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuService_GetSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).GetSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SkuService/GetSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).GetSku(ctx, req.(*GetSkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuService_ListSkusByActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkusByActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).ListSkusByActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SkuService/ListSkusByActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).ListSkusByActivity(ctx, req.(*ListSkusByActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkuService_DeleteSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkuServiceServer).DeleteSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SkuService/DeleteSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkuServiceServer).DeleteSku(ctx, req.(*DeleteSkuReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SkuService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.SkuService",
	HandlerType: (*SkuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSku",
			Handler:    _SkuService_CreateSku_Handler,
		},
		{
			MethodName: "UpdateSku",
			Handler:    _SkuService_UpdateSku_Handler,
		},
		{
			MethodName: "GetSku",
			Handler:    _SkuService_GetSku_Handler,
		},
		{
			MethodName: "ListSkusByActivity",
			Handler:    _SkuService_ListSkusByActivity_Handler,
		},
		{
			MethodName: "DeleteSku",
			Handler:    _SkuService_DeleteSku_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/rpc/seckill/proto/seckill.proto",
}

// SeckillServiceClient is the client API for SeckillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeckillServiceClient interface {
	AcquireToken(ctx context.Context, in *AcquireTokenReq, opts ...grpc.CallOption) (*AcquireTokenResp, error)
	SubmitOrder(ctx context.Context, in *SubmitOrderReq, opts ...grpc.CallOption) (*SubmitOrderResp, error)
	GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
}

type seckillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeckillServiceClient(cc grpc.ClientConnInterface) SeckillServiceClient {
	return &seckillServiceClient{cc}
}

func (c *seckillServiceClient) AcquireToken(ctx context.Context, in *AcquireTokenReq, opts ...grpc.CallOption) (*AcquireTokenResp, error) {
	out := new(AcquireTokenResp)
	err := c.cc.Invoke(ctx, "/seckill.SeckillService/AcquireToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServiceClient) SubmitOrder(ctx context.Context, in *SubmitOrderReq, opts ...grpc.CallOption) (*SubmitOrderResp, error) {
	out := new(SubmitOrderResp)
	err := c.cc.Invoke(ctx, "/seckill.SeckillService/SubmitOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seckillServiceClient) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	out := new(GetOrderResp)
	err := c.cc.Invoke(ctx, "/seckill.SeckillService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeckillServiceServer is the server API for SeckillService service.
// All implementations must embed UnimplementedSeckillServiceServer
// for forward compatibility
type SeckillServiceServer interface {
	AcquireToken(context.Context, *AcquireTokenReq) (*AcquireTokenResp, error)
	SubmitOrder(context.Context, *SubmitOrderReq) (*SubmitOrderResp, error)
	GetOrder(context.Context, *GetOrderReq) (*GetOrderResp, error)
	mustEmbedUnimplementedSeckillServiceServer()
}

// UnimplementedSeckillServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSeckillServiceServer struct {
}

func (UnimplementedSeckillServiceServer) AcquireToken(context.Context, *AcquireTokenReq) (*AcquireTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireToken not implemented")
}
func (UnimplementedSeckillServiceServer) SubmitOrder(context.Context, *SubmitOrderReq) (*SubmitOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedSeckillServiceServer) GetOrder(context.Context, *GetOrderReq) (*GetOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedSeckillServiceServer) mustEmbedUnimplementedSeckillServiceServer() {}

// UnsafeSeckillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeckillServiceServer will
// result in compilation errors.
type UnsafeSeckillServiceServer interface {
	mustEmbedUnimplementedSeckillServiceServer()
}

func RegisterSeckillServiceServer(s *grpc.Server, srv SeckillServiceServer) {
	s.RegisterService(&_SeckillService_serviceDesc, srv)
}

func _SeckillService_AcquireToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).AcquireToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SeckillService/AcquireToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).AcquireToken(ctx, req.(*AcquireTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SeckillService/SubmitOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).SubmitOrder(ctx, req.(*SubmitOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeckillService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeckillServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seckill.SeckillService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeckillServiceServer).GetOrder(ctx, req.(*GetOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SeckillService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.SeckillService",
	HandlerType: (*SeckillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireToken",
			Handler:    _SeckillService_AcquireToken_Handler,
		},
		{
			MethodName: "SubmitOrder",
			Handler:    _SeckillService_SubmitOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _SeckillService_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/rpc/seckill/proto/seckill.proto",
}
