// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: mall.proto

package orderservice

import (
	"context"

	"budgetmatch-sim/services/rpc/mall/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelOrderReq        = pb.CancelOrderReq
	CancelOrderResp       = pb.CancelOrderResp
	CreateOrderReq        = pb.CreateOrderReq
	CreateOrderResp       = pb.CreateOrderResp
	GetOrderReq           = pb.GetOrderReq
	GetOrderResp          = pb.GetOrderResp
	ListOrdersReq         = pb.ListOrdersReq
	ListOrdersResp        = pb.ListOrdersResp
	PayOrderReq           = pb.PayOrderReq
	PayOrderResp          = pb.PayOrderResp
	UpdateOrderStatusReq  = pb.UpdateOrderStatusReq
	UpdateOrderStatusResp = pb.UpdateOrderStatusResp

	OrderService interface {
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
		ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error)
		UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error)
		PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

func (m *defaultOrderService) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrderService) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrderService) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultOrderService) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*CancelOrderResp, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultOrderService) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusReq, opts ...grpc.CallOption) (*UpdateOrderStatusResp, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.UpdateOrderStatus(ctx, in, opts...)
}

func (m *defaultOrderService) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error) {
	client := pb.NewOrderServiceClient(m.cli.Conn())
	return client.PayOrder(ctx, in, opts...)
}
