// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package seckillservice

import (
	"context"

	"budgetmatch-sim/services/rpc/seckill/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcquireTokenReq        = pb.AcquireTokenReq
	AcquireTokenResp       = pb.AcquireTokenResp
	Activity               = pb.Activity
	CreateActivityReq      = pb.CreateActivityReq
	CreateActivityResp     = pb.CreateActivityResp
	CreateSkuReq           = pb.CreateSkuReq
	CreateSkuResp          = pb.CreateSkuResp
	DeleteActivityReq      = pb.DeleteActivityReq
	DeleteActivityResp     = pb.DeleteActivityResp
	DeleteSkuReq           = pb.DeleteSkuReq
	DeleteSkuResp          = pb.DeleteSkuResp
	GetActivityReq         = pb.GetActivityReq
	GetActivityResp        = pb.GetActivityResp
	GetOrderReq            = pb.GetOrderReq
	GetOrderResp           = pb.GetOrderResp
	GetSkuReq              = pb.GetSkuReq
	GetSkuResp             = pb.GetSkuResp
	ListActivitiesReq      = pb.ListActivitiesReq
	ListActivitiesResp     = pb.ListActivitiesResp
	ListSkusByActivityReq  = pb.ListSkusByActivityReq
	ListSkusByActivityResp = pb.ListSkusByActivityResp
	OfflineActivityReq     = pb.OfflineActivityReq
	OfflineActivityResp    = pb.OfflineActivityResp
	OnlineActivityReq      = pb.OnlineActivityReq
	OnlineActivityResp     = pb.OnlineActivityResp
	PreheatActivityReq     = pb.PreheatActivityReq
	PreheatActivityResp    = pb.PreheatActivityResp
	Sku                    = pb.Sku
	SubmitOrderReq         = pb.SubmitOrderReq
	SubmitOrderResp        = pb.SubmitOrderResp
	UpdateActivityReq      = pb.UpdateActivityReq
	UpdateActivityResp     = pb.UpdateActivityResp
	UpdateSkuReq           = pb.UpdateSkuReq
	UpdateSkuResp          = pb.UpdateSkuResp

	SeckillService interface {
		AcquireToken(ctx context.Context, in *AcquireTokenReq, opts ...grpc.CallOption) (*AcquireTokenResp, error)
		SubmitOrder(ctx context.Context, in *SubmitOrderReq, opts ...grpc.CallOption) (*SubmitOrderResp, error)
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
	}

	defaultSeckillService struct {
		cli zrpc.Client
	}
)

func NewSeckillService(cli zrpc.Client) SeckillService {
	return &defaultSeckillService{
		cli: cli,
	}
}

func (m *defaultSeckillService) AcquireToken(ctx context.Context, in *AcquireTokenReq, opts ...grpc.CallOption) (*AcquireTokenResp, error) {
	client := pb.NewSeckillServiceClient(m.cli.Conn())
	return client.AcquireToken(ctx, in, opts...)
}

func (m *defaultSeckillService) SubmitOrder(ctx context.Context, in *SubmitOrderReq, opts ...grpc.CallOption) (*SubmitOrderResp, error) {
	client := pb.NewSeckillServiceClient(m.cli.Conn())
	return client.SubmitOrder(ctx, in, opts...)
}

func (m *defaultSeckillService) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	client := pb.NewSeckillServiceClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}
