// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: seckill.proto

package skuservice

import (
	"context"

	"budgetmatch-sim/services/rpc/seckill/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcquireTokenReq        = pb.AcquireTokenReq
	AcquireTokenResp       = pb.AcquireTokenResp
	Activity               = pb.Activity
	CreateActivityReq      = pb.CreateActivityReq
	CreateActivityResp     = pb.CreateActivityResp
	CreateSkuReq           = pb.CreateSkuReq
	CreateSkuResp          = pb.CreateSkuResp
	DeleteActivityReq      = pb.DeleteActivityReq
	DeleteActivityResp     = pb.DeleteActivityResp
	DeleteSkuReq           = pb.DeleteSkuReq
	DeleteSkuResp          = pb.DeleteSkuResp
	GetActivityReq         = pb.GetActivityReq
	GetActivityResp        = pb.GetActivityResp
	GetOrderReq            = pb.GetOrderReq
	GetOrderResp           = pb.GetOrderResp
	GetSkuReq              = pb.GetSkuReq
	GetSkuResp             = pb.GetSkuResp
	ListActivitiesReq      = pb.ListActivitiesReq
	ListActivitiesResp     = pb.ListActivitiesResp
	ListSkusByActivityReq  = pb.ListSkusByActivityReq
	ListSkusByActivityResp = pb.ListSkusByActivityResp
	OfflineActivityReq     = pb.OfflineActivityReq
	OfflineActivityResp    = pb.OfflineActivityResp
	OnlineActivityReq      = pb.OnlineActivityReq
	OnlineActivityResp     = pb.OnlineActivityResp
	PreheatActivityReq     = pb.PreheatActivityReq
	PreheatActivityResp    = pb.PreheatActivityResp
	Sku                    = pb.Sku
	SubmitOrderReq         = pb.SubmitOrderReq
	SubmitOrderResp        = pb.SubmitOrderResp
	UpdateActivityReq      = pb.UpdateActivityReq
	UpdateActivityResp     = pb.UpdateActivityResp
	UpdateSkuReq           = pb.UpdateSkuReq
	UpdateSkuResp          = pb.UpdateSkuResp

	SkuService interface {
		CreateSku(ctx context.Context, in *CreateSkuReq, opts ...grpc.CallOption) (*CreateSkuResp, error)
		UpdateSku(ctx context.Context, in *UpdateSkuReq, opts ...grpc.CallOption) (*UpdateSkuResp, error)
		GetSku(ctx context.Context, in *GetSkuReq, opts ...grpc.CallOption) (*GetSkuResp, error)
		ListSkusByActivity(ctx context.Context, in *ListSkusByActivityReq, opts ...grpc.CallOption) (*ListSkusByActivityResp, error)
		DeleteSku(ctx context.Context, in *DeleteSkuReq, opts ...grpc.CallOption) (*DeleteSkuResp, error)
	}

	defaultSkuService struct {
		cli zrpc.Client
	}
)

func NewSkuService(cli zrpc.Client) SkuService {
	return &defaultSkuService{
		cli: cli,
	}
}

func (m *defaultSkuService) CreateSku(ctx context.Context, in *CreateSkuReq, opts ...grpc.CallOption) (*CreateSkuResp, error) {
	client := pb.NewSkuServiceClient(m.cli.Conn())
	return client.CreateSku(ctx, in, opts...)
}

func (m *defaultSkuService) UpdateSku(ctx context.Context, in *UpdateSkuReq, opts ...grpc.CallOption) (*UpdateSkuResp, error) {
	client := pb.NewSkuServiceClient(m.cli.Conn())
	return client.UpdateSku(ctx, in, opts...)
}

func (m *defaultSkuService) GetSku(ctx context.Context, in *GetSkuReq, opts ...grpc.CallOption) (*GetSkuResp, error) {
	client := pb.NewSkuServiceClient(m.cli.Conn())
	return client.GetSku(ctx, in, opts...)
}

func (m *defaultSkuService) ListSkusByActivity(ctx context.Context, in *ListSkusByActivityReq, opts ...grpc.CallOption) (*ListSkusByActivityResp, error) {
	client := pb.NewSkuServiceClient(m.cli.Conn())
	return client.ListSkusByActivity(ctx, in, opts...)
}

func (m *defaultSkuService) DeleteSku(ctx context.Context, in *DeleteSkuReq, opts ...grpc.CallOption) (*DeleteSkuResp, error) {
	client := pb.NewSkuServiceClient(m.cli.Conn())
	return client.DeleteSku(ctx, in, opts...)
}
