// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: agent.proto

package server

import (
	"context"

	"budgetmatch-sim/services/rpc/agent/internal/logic/recommendservice"
	"budgetmatch-sim/services/rpc/agent/internal/svc"
	"budgetmatch-sim/services/rpc/agent/pb"
)

type RecommendServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRecommendServiceServer
}

func NewRecommendServiceServer(svcCtx *svc.ServiceContext) *RecommendServiceServer {
	return &RecommendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendServiceServer) Recommend(ctx context.Context, in *pb.RecommendReq) (*pb.RecommendResp, error) {
	l := recommendservicelogic.NewRecommendLogic(ctx, s.svcCtx)
	return l.Recommend(in)
}
